<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;
use App\Models\Order\Store;

class StoreTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run($company = null)
    {
        Schema::connection('order')->disableForeignKeyConstraints();

        $Foodie = DB::connection('order')->table('store_types')->where('name','Foodie')->first()->id;
        $Grocery = DB::connection('order')->table('store_types')->where('name','Grocery')->first()->id;
        $Alcohol = DB::connection('order')->table('store_types')->where('name','Alcohol')->first()->id;
        $Flower = DB::connection('order')->table('store_types')->where('name','Flower')->first()->id;

        $country_id ='101';
        $city_id ='3659';
        $zone_id ='1';


        $stores = [
            ['store_type_id' => $Foodie,'store_name' =>'Thalapakatti','email' =>'thalapakatti@demo.com','password' =>'123456','store_location' =>'Chennai, Tamil Nadu, India','latitude' =>'13.0826802','longitude' =>'80.27071840000008','store_zipcode' =>'624001','country_id' => $country_id,'city_id' => $city_id,'zone_id' => $zone_id,'contact_person' =>'John','contact_number' =>'1','country_code' =>'91','picture' => url('/').'/images/order/stores/thalapakatti.png','store_packing_charges' =>'12.00','store_gst' =>'3','commission' =>'5','offer_min_amount' =>'200','offer_percent' => 3,'estimated_delivery_time' => 20,'description' =>'Delicious Briyani!!','currency_symbol' =>'$','free_delivery' => 0,'is_veg' =>'Pure Veg','rating' =>'3.50','is_bankdetail' => 1,'company_id' => $company],
['store_type_id' => $Foodie,'store_name' =>'KFC Demo','email' =>'kfc@demo.com','password' =>'123456','store_location' =>'Nungambakkam, Chennai, Tamil Nadu, India','latitude' =>'13.0569467','longitude' =>'80.24246900000003','store_zipcode' =>'123456','country_id' => $country_id,'city_id' => $city_id,'zone_id' => $zone_id,'contact_person' =>'kfc@demo.com','contact_number' =>'2','country_code' =>'91','picture' => url('/').'/images/order/stores/kfc_demo.png','store_packing_charges' =>'10.00','store_gst' =>'10','commission' =>'5','offer_min_amount' =>'100','offer_percent' => 5,'estimated_delivery_time' => 30,'description' =>'Burger Special!!','currency_symbol' =>'$','free_delivery' => 0,'is_veg' =>'Non Veg','rating' =>'3.10','is_bankdetail' => 0,'company_id' => $company],
['store_type_id' => $Foodie,'store_name' =>'Lassi Shop','email' =>'lassi@demo.com','password' =>'123456','store_location' =>'Teynampet, Chennai, Tamil Nadu, India','latitude' =>'13.0414559','longitude' =>'80.25201620000007','store_zipcode' =>'600018','country_id' => $country_id,'city_id' => $city_id,'zone_id' => $zone_id,'contact_person' =>'mcd','contact_number' =>'3','country_code' =>'91','picture' => url('/').'/images/order/stores/lassi_shop.png','store_packing_charges' =>'10.00','store_gst' =>'5','commission' =>'5','offer_min_amount' =>'100','offer_percent' => 5,'estimated_delivery_time' => 30,'description' =>'Amazing foods and offers!!','currency_symbol' =>'$','free_delivery' => 0,'is_veg' =>'Pure Veg','rating' =>'3.83','is_bankdetail' => 0,'company_id' => $company],
['store_type_id' => $Foodie,'store_name' =>'SeaShell','email' =>'seashell@demo.com','password' =>'123456','store_location' =>'Ikeja, Nigeria','latitude' =>'6.601838','longitude' =>'3.3514863000000332','store_zipcode' =>'625001','country_id' =>'160','city_id' =>'31317','zone_id' =>'6','contact_person' =>'Tenu','contact_number' =>'4','country_code' =>'91','picture' => url('/').'/images/order/stores/seashell.png','store_packing_charges' =>'5.00','store_gst' =>'5','commission' =>'0','offer_min_amount' =>'200','offer_percent' => 5,'estimated_delivery_time' => 20,'description' =>'Delicious!!','currency_symbol' =>'$','free_delivery' => 0,'is_veg' =>'Non Veg','rating' =>'5.00','is_bankdetail' => 0,'company_id' => $company],
['store_type_id' => $Foodie,'store_name' =>'Chowking nigeria','email' =>'chowking@demo.com','password' =>'123456','store_location' =>'D\'Podium International Event Center, Opposite Sunrise Chinese Restaurant, Adeniyi Jones Avenue, Ikeja, Nigeria','latitude' =>'6.6102083','longitude' =>'3.3452738999999383','store_zipcode' =>'321321','country_id' =>'160','city_id' =>'31317','zone_id' =>'6','contact_person' =>'Chow','contact_number' =>'9','country_code' =>'91','picture' => url('/').'/images/order/stores/chowking_nigeria.jpeg','store_packing_charges' =>'50.00','store_gst' =>'5','commission' =>'10','offer_min_amount' =>'1000','offer_percent' => 10,'estimated_delivery_time' => 30,'description' =>'Chowking asian food','currency_symbol' =>'$','free_delivery' => 0,'is_veg' =>'Non Veg','rating' =>'5.00','is_bankdetail' => 0,'company_id' => $company],
['store_type_id' => $Foodie,'store_name' =>'MOS Burger','email' =>'mos@demo.com','password' =>'123456','store_location' =>'Vadapalani, Chennai, Tamil Nadu, India','latitude' =>'13.0499711','longitude' =>'80.21213060000002','store_zipcode' =>'600937','country_id' => $country_id,'city_id' => $city_id,'zone_id' => $zone_id,'contact_person' =>'MOS','contact_number' =>'10','country_code' =>'91','picture' => url('/').'/images/order/stores/mos_burger.png','store_packing_charges' =>'10.00','store_gst' =>'5','commission' =>'5','offer_min_amount' =>'200','offer_percent' => 3,'estimated_delivery_time' => 30,'description' =>'MOS Food Services, Inc., doing business as MOS Burger, is a fast-food restaurant chain that originated in Japan.','currency_symbol' =>'$','free_delivery' => 0,'is_veg' =>'Pure Veg','rating' =>'5.00','is_bankdetail' => 0,'company_id' => $company],
['store_type_id' => $Foodie,'store_name' =>'Bonchon Chicken','email' =>'bonchon@demo.com','password' =>'123456','store_location' =>'Nigeria - Dubai - United Arab Emirates','latitude' =>'25.2148914','longitude' =>'55.174667099999965','store_zipcode' =>'54014','country_id' =>'160','city_id' =>'31317','zone_id' =>'6','contact_person' =>'Steffan','contact_number' =>'12','country_code' =>'234','picture' => url('/').'/images/order/stores/bonchon_chicken.png','store_packing_charges' =>'10.00','store_gst' =>'5','commission' =>'5','offer_min_amount' =>'100','offer_percent' => 2,'estimated_delivery_time' => 30,'description' =>'Bonchon Chicken is a South Korean-based international fried chicken restaurant franchise','currency_symbol' =>'$','free_delivery' => 0,'is_veg' =>'Non Veg','rating' =>'5.00','is_bankdetail' => 0,'company_id' => $company],
['store_type_id' => $Foodie,'store_name' =>'Marrybrown','email' =>'marrybrown@demo.com','password' =>'123456','store_location' =>'Etim Inyang Cres, Victoria Island, Lagos, Nigeria','latitude' =>'6.4331477','longitude' =>'3.436603900000023','store_zipcode' =>'6348736','country_id' =>'160','city_id' =>'31317','zone_id' =>'6','contact_person' =>'Mr.FInch','contact_number' =>'13','country_code' =>'234','picture' => url('/').'/images/order/stores/marrybrown.png','store_packing_charges' =>'10.00','store_gst' =>'5','commission' =>'5','offer_min_amount' =>'250','offer_percent' => 5,'estimated_delivery_time' => 30,'description' =>'Marrybrown Sdn Bhd is a Malaysian-based halal-certified fast food restaurant chain established in 1981. It was the first local fast food chain to franchise its business in Malaysia with more than 138 restaurants locally','currency_symbol' =>'$','free_delivery' => 0,'is_veg' =>'Pure Veg','rating' =>'5.00','is_bankdetail' => 0,'company_id' => $company],
['store_type_id' => $Foodie,'store_name' =>'Metisse Restaurant','email' =>'metisse@demo.com','password' =>'123456','store_location' =>'14b Agoro Odiyan St, Victoria Island, Lagos, Nigeria','latitude' =>'6.429230599999999','longitude' =>'3.418969000000061','store_zipcode' =>'46347','country_id' =>'160','city_id' =>'31317','zone_id' =>'6','contact_person' =>'Mr.Anderson','contact_number' =>'14','country_code' =>'234','picture' => url('/').'/images/order/stores/metisse_restaurant.png','store_packing_charges' =>'12.00','store_gst' =>'5','commission' =>'4','offer_min_amount' =>'200','offer_percent' => 5,'estimated_delivery_time' => 30,'description' =>'An upscale restaurant ðŸ´ that serves healthy meals at reasonable prices.','currency_symbol' =>'$','free_delivery' => 0,'is_veg' =>'Pure Veg','rating' =>'5.00','is_bankdetail' => 0,'company_id' => $company],
['store_type_id' => $Foodie,'store_name' =>'Cactus Restaurant','email' =>'cactus@demo.com','password' =>'123456','store_location' =>'Nigerian Law School Lagos Campus Victoria Island Lagos, Ozumba Mbadiwe Rd, Victoria Island, Lagos, Nigeria','latitude' =>'6.4384716','longitude' =>'3.4289400000000114','store_zipcode' =>'43110','country_id' =>'160','city_id' =>'31317','zone_id' =>'6','contact_person' =>'Mr.Jacque','contact_number' =>'17','country_code' =>'234','picture' => url('/').'/images/order/stores/cactus_restaurant.png','store_packing_charges' =>'10.00','store_gst' =>'5','commission' =>'5','offer_min_amount' =>'100','offer_percent' => 2,'estimated_delivery_time' => 30,'description' =>'Cactus Restaurant is a fantastic place to propose, you would enjoy the ambience and the gentle breeze by the water side.','currency_symbol' =>'$','free_delivery' => 0,'is_veg' =>'Pure Veg','rating' =>'5.00','is_bankdetail' => 0,'company_id' => $company],
['store_type_id' => $Foodie,'store_name' =>'Jevinik Restaurant','email' =>'jevinik@demo.com','password' =>'123456','store_location' =>'14b Agoro Odiyan St, Victoria Island, Lagos, Nigeria','latitude' =>'6.429230599999999','longitude' =>'3.418969000000061','store_zipcode' =>'634634','country_id' =>'160','city_id' =>'31317','zone_id' =>'6','contact_person' =>'Mr.Kallis','contact_number' =>'20','country_code' =>'234','picture' => url('/').'/images/order/stores/jevinik_restaurant.png','store_packing_charges' =>'10.00','store_gst' =>'5','commission' =>'5','offer_min_amount' =>'100','offer_percent' => 5,'estimated_delivery_time' => 30,'description' =>'The fried rice had the same beans all over it. It was just too much. I loved my son\'s rice and stew when I had a taste of it and wished I had ordered that.','currency_symbol' =>'$','free_delivery' => 0,'is_veg' =>'Pure Veg','rating' =>'5.00','is_bankdetail' => 0,'company_id' => $company],
['store_type_id' => $Foodie,'store_name' =>'Sala','email' =>'sala@demo.com','password' =>'123456','store_location' =>'Guindy, Chennai, Tamil Nadu, India','latitude' =>'13.0066625','longitude' =>'80.22063690000004','store_zipcode' =>'3421','country_id' => $country_id,'city_id' => $city_id,'zone_id' => $zone_id,'contact_person' =>'Mr.Noam','contact_number' =>'30','country_code' =>'91','picture' => url('/').'/images/order/stores/sala.jpg','store_packing_charges' =>'30.00','store_gst' =>'3','commission' =>'4','offer_min_amount' =>'500','offer_percent' => 5,'estimated_delivery_time' => 25,'description' =>'fvfv','currency_symbol' =>'$','free_delivery' => 0,'is_veg' =>'Non Veg','rating' =>'5.00','is_bankdetail' => 0,'company_id' => $company],
['store_type_id' => $Foodie,'store_name' =>'Hungry Nation','email' =>'hungry@demo.com','password' =>'123456','store_location' =>'Adeniyi Jones Avenue, Ikeja, Nigeria','latitude' =>'6.6073002','longitude' =>'3.3410261999999875','store_zipcode' =>'23401','country_id' =>'160','city_id' =>'31317','zone_id' =>'6','contact_person' =>'','contact_number' =>'34','country_code' =>'91','picture' => url('/').'/images/order/stores/hungry_nation.png','store_packing_charges' =>'100.00','store_gst' =>'5','commission' =>'15','offer_min_amount' =>'1200','offer_percent' => 0,'estimated_delivery_time' => 35,'description' =>'Your Meal Well Dished','currency_symbol' =>'$','free_delivery' => 0,'is_veg' =>'Non Veg','rating' =>'5.00','is_bankdetail' => 0,'company_id' => $company],
['store_type_id' => $Grocery,'store_name' =>'AlbertSons','email' =>'albertsons@demo.com','password' =>'123456','store_location' =>'T. Nagar, Chennai, Tamil Nadu, India','latitude' =>'13.0417591','longitude' =>'80.23407610000004','store_zipcode' =>'623991','country_id' => $country_id,'city_id' => $city_id,'zone_id' => $zone_id,'contact_person' =>'Joel','contact_number' =>'5','country_code' =>'91','picture' => url('/').'/images/order/stores/albertsons.png','store_packing_charges' =>'5.00','store_gst' =>'5','commission' =>'0','offer_min_amount' =>'100','offer_percent' => 5,'estimated_delivery_time' => 20,'description' =>'Home Needs','currency_symbol' =>'$','free_delivery' => 0,'is_veg' =>'','rating' =>'5.00','is_bankdetail' => 0,'company_id' => $company],
['store_type_id' => $Grocery,'store_name' =>'Aldi','email' =>'aldi@demo.com','password' =>'123456','store_location' =>'Teynampet, Chennai, Tamil Nadu, India','latitude' =>'13.0414559','longitude' =>'80.25201620000007','store_zipcode' =>'600091','country_id' => $country_id,'city_id' => $city_id,'zone_id' => $zone_id,'contact_person' =>'james','contact_number' =>'6','country_code' =>'91','picture' => url('/').'/images/order/stores/aldi.png','store_packing_charges' =>'5.00','store_gst' =>'5','commission' =>'0','offer_min_amount' =>'100','offer_percent' => 5,'estimated_delivery_time' => 20,'description' =>'Grocery','currency_symbol' =>'$','free_delivery' => 1,'is_veg' =>'Pure Veg','rating' =>'5.00','is_bankdetail' => 0,'company_id' => $company],
['store_type_id' => $Grocery,'store_name' =>'Kroger Shop','email' =>'kroger@demo.com','password' =>'123456','store_location' =>'Villupuram, Tamil Nadu, India','latitude' =>'11.927783','longitude' =>'79.48257850000005','store_zipcode' =>'623440','country_id' => $country_id,'city_id' => $city_id,'zone_id' => $zone_id,'contact_person' =>'8765434444','contact_number' =>'7','country_code' =>'91','picture' => url('/').'/images/order/stores/kroger_shop.png','store_packing_charges' =>'4.00','store_gst' =>'5','commission' =>'5','offer_min_amount' =>'100','offer_percent' => 5,'estimated_delivery_time' => 20,'description' =>'Kroger shop','currency_symbol' =>'$','free_delivery' => 1,'is_veg' =>'Pure Veg','rating' =>'5.00','is_bankdetail' => 0,'company_id' => $company],
['store_type_id' => $Grocery,'store_name' =>'Walmart','email' =>'walmart@demo.com','password' =>'123456','store_location' =>'Nigeria - Dubai - United Arab Emirates','latitude' =>'25.2148914','longitude' =>'55.174667099999965','store_zipcode' =>'346554','country_id' =>'160','city_id' =>'31317','zone_id' =>'6','contact_person' =>'Mr.Steffan','contact_number' =>'27','country_code' =>'234','picture' => url('/').'/images/order/stores/walmart.png','store_packing_charges' =>'10.00','store_gst' =>'5','commission' =>'0','offer_min_amount' =>'50','offer_percent' => 0,'estimated_delivery_time' => 20,'description' =>'Walmart Inc. is an American multinational retail corporation that operates a chain of hypermarkets, discount department stores, and grocery stores. Headquartered in Bentonville,','currency_symbol' =>'$','free_delivery' => 1,'is_veg' =>'','rating' =>'5.00','is_bankdetail' => 0,'company_id' => $company],
['store_type_id' => $Grocery,'store_name' =>'Whole Foods','email' =>'whole@demo.com','password' =>'123456','store_location' =>'Keffi Street, Abuja, Nigeria','latitude' =>'9.0162181','longitude' =>'7.490252499999997','store_zipcode' =>'546546','country_id' =>'160','city_id' =>'31317','zone_id' =>'6','contact_person' =>'Mr.Braydon','contact_number' =>'28','country_code' =>'234','picture' => url('/').'/images/order/stores/whole_foods.png','store_packing_charges' =>'10.00','store_gst' =>'5','commission' =>'0','offer_min_amount' =>'','offer_percent' => 0,'estimated_delivery_time' => 20,'description' =>'Whole Foods Market Inc. is an American supermarket chain which exclusively sells products free from hydrogenated fats and artificial colors, flavors, preservatives, and sweeteners. Being the only USDA Certified Organic grocer in the United States, the chain is popularly known for its organic selections','currency_symbol' =>'$','free_delivery' => 0,'is_veg' =>'','rating' =>'5.00','is_bankdetail' => 0,'company_id' => $company],
['store_type_id' => $Grocery,'store_name' =>'ShopRite','email' =>'shoprite@demo.com','password' =>'123456','store_location' =>'6 Ebitu Ukiwe St, Jabi, Abuja, Nigeria','latitude' =>'9.063675199999999','longitude' =>'7.423823500000026','store_zipcode' =>'6555665','country_id' =>'160','city_id' =>'31317','zone_id' =>'6','contact_person' =>'','contact_number' =>'29','country_code' =>'234','picture' => url('/').'/images/order/stores/shoprite.png','store_packing_charges' =>'10.00','store_gst' =>'5','commission' =>'2','offer_min_amount' =>'100','offer_percent' => 0,'estimated_delivery_time' => 20,'description' =>'ShopRite originated in 1946, when a Del Monte Foods sales representative talked to independent grocers in Newark, New Jersey. The grocers were having problems getting reasonable prices for wholesale goods. The Del Monte representative suggested the grocers try cooperative buying. Seven of the grocers agreed; paying $1,000 each to launch Wakefern Foods, which was incorporated on December 5, 1946. In 1951, the name ShopRite was created.','currency_symbol' =>'$','free_delivery' => 1,'is_veg' =>'','rating' =>'5.00','is_bankdetail' => 0,'company_id' => $company],
['store_type_id' => $Grocery,'store_name' =>'Marketside','email' =>'marketside@demo.com','password' =>'123456','store_location' =>'6 Ebitu Ukiwe St, Jabi, Abuja, Nigeria','latitude' =>'9.063675199999999','longitude' =>'7.423823500000026','store_zipcode' =>'754654','country_id' =>'160','city_id' =>'31317','zone_id' =>'6','contact_person' =>'Mr.Noam','contact_number' =>'31','country_code' =>'227','picture' => url('/').'/images/order/stores/marketside.png','store_packing_charges' =>'10.00','store_gst' =>'0','commission' =>'0','offer_min_amount' =>'100','offer_percent' => 0,'estimated_delivery_time' => 20,'description' =>'Marketside was a chain of grocery stores owned by Walmart in the metro Phoenix area. The stores were opened in October 2008 and closed in October 2011. Only four locations operated, in Chandler; Gilbert; Mesa; and Tempe.','currency_symbol' =>'$','free_delivery' => 0,'is_veg' =>'Pure Veg','rating' =>'5.00','is_bankdetail' => 0,'company_id' => $company],
['store_type_id' => $Grocery,'store_name' =>'Southeastern Grocers','email' =>'southeastern@demo.com','password' =>'123456','store_location' =>'14b Agoro Odiyan St, Victoria Island, Lagos, Nigeria','latitude' =>'6.429230599999999','longitude' =>'3.418969000000061','store_zipcode' =>'643534','country_id' =>'160','city_id' =>'31317','zone_id' =>'6','contact_person' =>'9876565454','contact_number' =>'32','country_code' =>'234','picture' => url('/').'/images/order/stores/southeastern_grocers.png','store_packing_charges' =>'10.00','store_gst' =>'5','commission' =>'0','offer_min_amount' =>'100','offer_percent' => 0,'estimated_delivery_time' => 20,'description' =>'Southeastern Grocers is a supermarket portfolio headquartered in Jacksonville, Florida. The portfolio was created by Lone Star Funds in September 2013 as the new parent company for BI-LO','currency_symbol' =>'$','free_delivery' => 0,'is_veg' =>'','rating' =>'5.00','is_bankdetail' => 0,'company_id' => $company],
['store_type_id' => $Grocery,'store_name' =>'Food Stuff','email' =>'food@demo.com','password' =>'123456','store_location' =>'Chennai, Tamil Nadu, India','latitude' =>'13.0826802','longitude' =>'80.27071840000008','store_zipcode' =>'0000','country_id' => $country_id,'city_id' => $city_id,'zone_id' => $zone_id,'contact_person' =>'Me','contact_number' =>'33','country_code' =>'973','picture' => url('/').'/images/order/stores/food_stuff.png','store_packing_charges' =>'20.00','store_gst' =>'0','commission' =>'0','offer_min_amount' =>'','offer_percent' => 0,'estimated_delivery_time' => 94,'description' =>'','currency_symbol' =>'$','free_delivery' => 0,'is_veg' =>'Non Veg','rating' =>'5.00','is_bankdetail' => 1,'company_id' => $company],
['store_type_id' => $Alcohol ,'store_name' =>'Beer Temple','email' =>'beer@demo.com','password' =>'123456','store_location' =>'Abuja-Keffi Road, Nigeria','latitude' =>'8.859643999999998','longitude' =>'7.8295797000000675','store_zipcode' =>'5432','country_id' =>'160','city_id' =>'31317','zone_id' =>'6','contact_person' =>'Mr.Braydon','contact_number' =>'11','country_code' =>'91','picture' => url('/').'/images/order/stores/beer_temple.png','store_packing_charges' =>'100.00','store_gst' =>'5','commission' =>'5','offer_min_amount' =>'500','offer_percent' => 15,'estimated_delivery_time' => 20,'description' =>'Talking to a drunk person was like talking to an extremely happy','currency_symbol' =>'$','free_delivery' => 0,'is_veg' =>'','rating' =>'5.00','is_bankdetail' => 0,'company_id' => $company],
['store_type_id' => $Alcohol ,'store_name' =>'Go Cheers','email' =>'go@demo.com','password' =>'123456','store_location' =>'Chida market, Abuja, Nigeria','latitude' =>'9.071899','longitude' =>'7.434586800000034','store_zipcode' =>'6543','country_id' =>'160','city_id' =>'31317','zone_id' =>'6','contact_person' =>'Mr.Nikolaj','contact_number' =>'15','country_code' =>'91','picture' => url('/').'/images/order/stores/go_cheers.png','store_packing_charges' =>'75.00','store_gst' =>'5','commission' =>'5','offer_min_amount' =>'500','offer_percent' => 20,'estimated_delivery_time' => 20,'description' =>'Alcohol is a depressant drug. It slows down varioussections of the brain and the central nervous system.This affects your ability to control your behaviour and your bodily functions, like thinking, talking, walking and even breathing.','currency_symbol' =>'$','free_delivery' => 0,'is_veg' =>'','rating' =>'5.00','is_bankdetail' => 0,'company_id' => $company],
['store_type_id' => $Alcohol ,'store_name' =>'Drinkie\'Z','email' =>'drinkie@demo.com','password' =>'123456','store_location' =>'194/199 Zuba Garki Rd, Gwarinpa, Abuja, Nigeria','latitude' =>'9.0674125','longitude' =>'7.4007431','store_zipcode' =>'7654','country_id' =>'160','city_id' =>'31317','zone_id' =>'6','contact_person' =>'Mr.Ethan','contact_number' =>'16','country_code' =>'91','picture' => url('/').'/images/order/stores/drinkie\'z.png','store_packing_charges' =>'80.00','store_gst' =>'5','commission' =>'5','offer_min_amount' =>'600','offer_percent' => 12,'estimated_delivery_time' => 20,'description' =>'Alcohol is a drug.
It is classed as a depressant, meaning that it slows down vital functionsâ€”resulting in slurred speech, unsteady movement, disturbed perceptions and an inability to react quickly.','currency_symbol' =>'$','free_delivery' => 0,'is_veg' =>'','rating' =>'5.00','is_bankdetail' => 0,'company_id' => $company],
['store_type_id' => $Alcohol ,'store_name' =>'Dranker\'s Park','email' =>'dranker@demo.com','password' =>'123456','store_location' =>'8 Ebitu Ukiwe St, Jabi, Abuja, Nigeria','latitude' =>'9.063869','longitude' =>'7.423817099999951','store_zipcode' =>'8765','country_id' =>'160','city_id' =>'31317','zone_id' =>'6','contact_person' =>'Mr.Felix','contact_number' =>'18','country_code' =>'91','picture' => url('/').'/images/order/stores/dranker\'s_park.png','store_packing_charges' =>'50.00','store_gst' =>'6','commission' =>'2','offer_min_amount' =>'400','offer_percent' => 6,'estimated_delivery_time' => 20,'description' =>'I feel sorry for people who don\'t drink. They wake up in the morning and that\'s the best they\'re going to feel all day.','currency_symbol' =>'$','free_delivery' => 0,'is_veg' =>'','rating' =>'5.00','is_bankdetail' => 0,'company_id' => $company],
['store_type_id' => $Alcohol ,'store_name' =>'Liquor Palace','email' =>'liquor@demo.com','password' =>'123456','store_location' =>'6 Ebitu Ukiwe St, Jabi, Abuja, Nigeria','latitude' =>'9.063675199999999','longitude' =>'7.423823500000026','store_zipcode' =>'9876','country_id' =>'160','city_id' =>'31317','zone_id' =>'6','contact_person' =>'Mr.Noam','contact_number' =>'19','country_code' =>'91','picture' => url('/').'/images/order/stores/liquor_palace.png','store_packing_charges' =>'60.00','store_gst' =>'8','commission' =>'4','offer_min_amount' =>'300','offer_percent' => 8,'estimated_delivery_time' => 20,'description' =>'Dear Alcohol, we had a deal, you were going to make me funnier, sexier, more intelligent and a better dancer. I saw the video, we need to talk.','currency_symbol' =>'$','free_delivery' => 0,'is_veg' =>'','rating' =>'5.00','is_bankdetail' => 0,'company_id' => $company],
['store_type_id' => $Flower,'store_name' =>'1800 Flower','email' =>'1800@demo.com','password' =>'123456','store_location' =>'Besant Nagar Beach, Elliots Beach, Besant Nagar, Chennai, Tamil Nadu, India','latitude' =>'12.9988983','longitude' =>'80.27185559999998','store_zipcode' =>'654456','country_id' => $country_id,'city_id' => $city_id,'zone_id' => $zone_id,'contact_person' =>'Smith','contact_number' =>'8','country_code' =>'91','picture' => url('/').'/images/order/stores/1800_flower.png','store_packing_charges' =>'10.00','store_gst' =>'3','commission' =>'3','offer_min_amount' =>'100','offer_percent' => 3,'estimated_delivery_time' => 20,'description' =>'Aromatic Flowers!!','currency_symbol' =>'$','free_delivery' => 1,'is_veg' =>'','rating' =>'5.00','is_bankdetail' => 0,'company_id' => $company],
['store_type_id' => $Flower,'store_name' =>'Ferns and Petals','email' =>'ferns@demo.com','password' =>'123456','store_location' =>'Teynampet, Chennai, Tamil Nadu, India','latitude' =>'13.0414559','longitude' =>'80.25201620000007','store_zipcode' =>'625443','country_id' => $country_id,'city_id' => $city_id,'zone_id' => $zone_id,'contact_person' =>'Tenu','contact_number' =>'21','country_code' =>'91','picture' => url('/').'/images/order/stores/ferns_and_petals.png','store_packing_charges' =>'2.00','store_gst' =>'2','commission' =>'2','offer_min_amount' =>'200','offer_percent' => 5,'estimated_delivery_time' => 20,'description' =>'Fresh flowers for occasions!!','currency_symbol' =>'$','free_delivery' => 0,'is_veg' =>'','rating' =>'5.00','is_bankdetail' => 0,'company_id' => $company],
['store_type_id' => $Flower,'store_name' =>'Fussion Florist','email' =>'fussiondemo.com','password' =>'123456','store_location' =>'Keffi Street, Abuja, Nigeria','latitude' =>'9.0162181','longitude' =>'7.490252499999997','store_zipcode' =>'2345','country_id' =>'160','city_id' =>'31317','zone_id' =>'6','contact_person' =>'Mr.Gustaw','contact_number' =>'22','country_code' =>'91','picture' => url('/').'/images/order/stores/fussion_florist.png','store_packing_charges' =>'50.00','store_gst' =>'15','commission' =>'4','offer_min_amount' =>'300','offer_percent' => 25,'estimated_delivery_time' => 20,'description' =>'Our flower delivery platform comprises of a team with strong technological and operations experience which enables us to deliver fresh flowers at the cheapest prices available .In addition to delivering flowers, we also strive to make that special occasion for you and your loved ones even more special by delivering surprise with lovely flowers.','currency_symbol' =>'$','free_delivery' => 0,'is_veg' =>'','rating' =>'5.00','is_bankdetail' => 0,'company_id' => $company],
['store_type_id' => $Flower,'store_name' =>'Just FlowerZ','email' =>'just@demo.com','password' =>'123456','store_location' =>'Chida market, Abuja, Nigeria','latitude' =>'9.071899','longitude' =>'7.434586800000034','store_zipcode' =>'2312','country_id' =>'160','city_id' =>'31317','zone_id' =>'6','contact_person' =>'Mr.Damian','contact_number' =>'23','country_code' =>'91','picture' => url('/').'/images/order/stores/just_flowerz.png','store_packing_charges' =>'45.00','store_gst' =>'6','commission' =>'5','offer_min_amount' =>'300','offer_percent' => 5,'estimated_delivery_time' => 20,'description' =>'Deliver the best quality - fresh cut flowers in more than 220 cities with the help of our strong affiliate network and channel stores. Each and every one of our flowers is handpicked at the right stage of bloom by our expert florists in your cities.','currency_symbol' =>'$','free_delivery' => 0,'is_veg' =>'','rating' =>'5.00','is_bankdetail' => 0,'company_id' => $company],
['store_type_id' => $Flower,'store_name' =>'Royal Blooms','email' =>'royal@demo.com','password' =>'123456','store_location' =>'194/199 Zuba Garki Rd, Gwarinpa, Abuja, Nigeria','latitude' =>'9.0674125','longitude' =>'7.4007431','store_zipcode' =>'2121','country_id' =>'160','city_id' =>'31317','zone_id' =>'6','contact_person' =>'Mr.Artem','contact_number' =>'24','country_code' =>'91','picture' => url('/').'/images/order/stores/royal_blooms.png','store_packing_charges' =>'50.00','store_gst' =>'3','commission' =>'3','offer_min_amount' =>'400','offer_percent' => 3,'estimated_delivery_time' => 20,'description' =>'The original "Flowers in a Gift" collection has expanded over the decades to include everything from coffee mugs to serving pitchers. Wherever you see the "Flowers in a Gift" symbol, you know your recipient isn\'t just getting flowers, he or she will also receive a keepsake they can treasure for years. View our "Flowers in a Gift" collection.','currency_symbol' =>'$','free_delivery' => 0,'is_veg' =>'','rating' =>'5.00','is_bankdetail' => 0,'company_id' => $company],
['store_type_id' => $Flower,'store_name' =>'Flora','email' =>'flora@demo.com','password' =>'123456','store_location' =>'8 Ebitu Ukiwe St, Jabi, Abuja, Nigeria','latitude' =>'9.063869','longitude' =>'7.423817099999951','store_zipcode' =>'3454','country_id' =>'160','city_id' =>'31317','zone_id' =>'6','contact_person' =>'Mr.Noam','contact_number' =>'25','country_code' =>'91','picture' => url('/').'/images/order/stores/flora.png','store_packing_charges' =>'30.00','store_gst' =>'2','commission' =>'4','offer_min_amount' =>'600','offer_percent' => 3,'estimated_delivery_time' => 20,'description' =>'The cornerstone of Book My Flowers was laid in the year 2009 with an objective to deliver smiles across the globe. Book My Flowers is a one-stop destination to shop for a wide array of gifts, from flowers and cakes to chocolates and gift baskets. Be it any occasion, you can trust Book My Flowers, when it comes to expressing your love and affection to your dear ones in the most beautiful manner.','currency_symbol' =>'$','free_delivery' => 0,'is_veg' =>'','rating' =>'5.00','is_bankdetail' => 0,'company_id' => $company],
['store_type_id' => $Flower,'store_name' =>'MooMix','email' =>'moomix@demo.com','password' =>'123456','store_location' =>'6 Ebitu Ukiwe St, Jabi, Abuja, Nigeria','latitude' =>'9.063675199999999','longitude' =>'7.423823500000026','store_zipcode' =>'5645','country_id' =>'160','city_id' =>'31317','zone_id' =>'6','contact_person' =>'Mr.Patrick','contact_number' =>'26','country_code' =>'91','picture' => url('/').'/images/order/stores/moomix.png','store_packing_charges' =>'45.00','store_gst' =>'3','commission' =>'0','offer_min_amount' =>'500','offer_percent' => 15,'estimated_delivery_time' => 20,'description' =>'We do not just provide flowers in various ways but, we also deliver them on the doorstep of those you want them delivered to.','currency_symbol' =>'$','free_delivery' => 0,'is_veg' =>'','rating' =>'5.00','is_bankdetail' => 0,'company_id' => $company]
        ];


        foreach ($stores as $store) {
            $store['password'] = Hash::make($store['password']);
            $store['currency'] ='$';
            Store::create($store);
        }
        
        Schema::connection('order')->enableForeignKeyConstraints();
    }
}
