<?php

use Illuminate\Database\Seeder;

class StoreItemTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run($company = null)
    {
        Schema::connection('order')->disableForeignKeyConstraints();

        $Thalapakatti  = DB::connection('order')->table('stores')->where('company_id', $company)->where('store_name','Thalapakatti')->first()->id;
        $KFC_Demo  = DB::connection('order')->table('stores')->where('company_id', $company)->where('store_name','KFC Demo')->first()->id;
        $Lassi_Shop  = DB::connection('order')->table('stores')->where('company_id', $company)->where('store_name','Lassi Shop')->first()->id;
        $SeaShell  = DB::connection('order')->table('stores')->where('company_id', $company)->where('store_name','SeaShell')->first()->id;
        $AlbertSons  = DB::connection('order')->table('stores')->where('company_id', $company)->where('store_name','AlbertSons')->first()->id;
        $Aldi  = DB::connection('order')->table('stores')->where('company_id', $company)->where('store_name','Aldi')->first()->id;
        $Kroger_Shop  = DB::connection('order')->table('stores')->where('company_id', $company)->where('store_name','Kroger Shop')->first()->id;
        $_Flower  = DB::connection('order')->table('stores')->where('company_id', $company)->where('store_name','1800 Flower')->first()->id;
        $Chowking_nigeria  = DB::connection('order')->table('stores')->where('company_id', $company)->where('store_name','Chowking nigeria')->first()->id;
        $MOS_Burger  = DB::connection('order')->table('stores')->where('company_id', $company)->where('store_name','MOS Burger')->first()->id;
        $Beer_Temple  = DB::connection('order')->table('stores')->where('company_id', $company)->where('store_name','Beer Temple')->first()->id;
        $Bonchon_Chicken  = DB::connection('order')->table('stores')->where('company_id', $company)->where('store_name','Bonchon Chicken')->first()->id;
        $Marrybrown  = DB::connection('order')->table('stores')->where('company_id', $company)->where('store_name','Marrybrown')->first()->id;
        $Metisse_Restaurant  = DB::connection('order')->table('stores')->where('company_id', $company)->where('store_name','Metisse Restaurant')->first()->id;
        $Go_Cheers  = DB::connection('order')->table('stores')->where('company_id', $company)->where('store_name','Go Cheers')->first()->id;
        $Drinkie  = DB::connection('order')->table('stores')->where('company_id', $company)->where('store_name','Drinkie\'Z')->first()->id;
        $Cactus_Restaurant  = DB::connection('order')->table('stores')->where('company_id', $company)->where('store_name','Cactus Restaurant')->first()->id;
        $Drankers_Park  = DB::connection('order')->table('stores')->where('company_id', $company)->where('store_name','Dranker\'s Park')->first()->id;
        $Liquor_Palace  = DB::connection('order')->table('stores')->where('company_id', $company)->where('store_name','Liquor Palace')->first()->id;
        $Jevinik_Restaurant  = DB::connection('order')->table('stores')->where('company_id', $company)->where('store_name','Jevinik Restaurant')->first()->id;
        $Ferns_and_Petals  = DB::connection('order')->table('stores')->where('company_id', $company)->where('store_name','Ferns and Petals')->first()->id;
        $Fussion_Florist  = DB::connection('order')->table('stores')->where('company_id', $company)->where('store_name','Fussion Florist')->first()->id;
        $Just_FlowerZ  = DB::connection('order')->table('stores')->where('company_id', $company)->where('store_name','Just FlowerZ')->first()->id;
        $Royal_Blooms  = DB::connection('order')->table('stores')->where('company_id', $company)->where('store_name','Royal Blooms')->first()->id;
        $Flora = DB::connection('order')->table('stores')->where('company_id', $company)->where('store_name','Flora')->first()->id;
        $MooMix  = DB::connection('order')->table('stores')->where('company_id', $company)->where('store_name','MooMix')->first()->id;
        $Walmart  = DB::connection('order')->table('stores')->where('company_id', $company)->where('store_name','Walmart')->first()->id;
        $Whole_Foods  = DB::connection('order')->table('stores')->where('company_id', $company)->where('store_name','Whole Foods')->first()->id;
        $ShopRite  = DB::connection('order')->table('stores')->where('company_id', $company)->where('store_name','ShopRite')->first()->id;
        $Sala  = DB::connection('order')->table('stores')->where('company_id', $company)->where('store_name','Sala')->first()->id;
        $Marketside  = DB::connection('order')->table('stores')->where('company_id', $company)->where('store_name','Marketside')->first()->id;
        $Southeastern_Grocers  = DB::connection('order')->table('stores')->where('company_id', $company)->where('store_name','Southeastern Grocers')->first()->id;
        $Food_Stuff  = DB::connection('order')->table('stores')->where('company_id', $company)->where('store_name','Food Stuff')->first()->id;
        $Hungry_Nation  = DB::connection('order')->table('stores')->where('company_id', $company)->where('store_name','Hungry Nation')->first()->id; 

        $Veg  = DB::connection('order')->table('store_categories')->where('company_id', $company)->where('store_category_name','Veg')->first()->id;
$Non_Vegetarian  = DB::connection('order')->table('store_categories')->where('company_id', $company)->where('store_category_name','Non-Vegetarian')->first()->id;
$Non_Vegetarian  = DB::connection('order')->table('store_categories')->where('company_id', $company)->where('store_category_name','Non-Vegetarian')->first()->id;
$Vegetarian  = DB::connection('order')->table('store_categories')->where('company_id', $company)->where('store_category_name','Vegetarian')->first()->id;
$Burger  = DB::connection('order')->table('store_categories')->where('company_id', $company)->where('store_category_name','Burger')->first()->id;
$Beverages  = DB::connection('order')->table('store_categories')->where('company_id', $company)->where('store_category_name','Beverages')->first()->id;
$Breakfast_and_cereal  = DB::connection('order')->table('store_categories')->where('company_id', $company)->where('store_category_name','Breakfast and cereal')->first()->id;
$Flowers  = DB::connection('order')->table('store_categories')->where('company_id', $company)->where('store_category_name','Flowers')->first()->id;
$Diary  = DB::connection('order')->table('store_categories')->where('company_id', $company)->where('store_category_name','Diary')->first()->id;
$Meat  = DB::connection('order')->table('store_categories')->where('company_id', $company)->where('store_category_name','Meat')->first()->id;
$Pantry  = DB::connection('order')->table('store_categories')->where('company_id', $company)->where('store_category_name','Pantry')->first()->id;
$Bakery  = DB::connection('order')->table('store_categories')->where('company_id', $company)->where('store_category_name','Bakery')->first()->id;
$Frozen  = DB::connection('order')->table('store_categories')->where('company_id', $company)->where('store_category_name','Frozen')->first()->id;
$HouseHold  = DB::connection('order')->table('store_categories')->where('company_id', $company)->where('store_category_name','HouseHold')->first()->id;
$Same_Day_Flowers  = DB::connection('order')->table('store_categories')->where('company_id', $company)->where('store_category_name','Same Day Flowers')->first()->id;
$Birthday  = DB::connection('order')->table('store_categories')->where('company_id', $company)->where('store_category_name','Birthday')->first()->id;
$Occasions  = DB::connection('order')->table('store_categories')->where('company_id', $company)->where('store_category_name','Occasions')->first()->id;
$Rice  = DB::connection('order')->table('store_categories')->where('company_id', $company)->where('store_category_name','Rice')->first()->id;
$Veg  = DB::connection('order')->table('store_categories')->where('company_id', $company)->where('store_category_name','Veg')->first()->id;
$Wine  = DB::connection('order')->table('store_categories')->where('company_id', $company)->where('store_category_name','Wine')->first()->id;
$Vodka  = DB::connection('order')->table('store_categories')->where('company_id', $company)->where('store_category_name','Vodka')->first()->id;
$Gin  = DB::connection('order')->table('store_categories')->where('company_id', $company)->where('store_category_name','Gin')->first()->id;
$Non_Veg  = DB::connection('order')->table('store_categories')->where('company_id', $company)->where('store_category_name','Non-Veg')->first()->id;
$Roses  = DB::connection('order')->table('store_categories')->where('company_id', $company)->where('store_category_name','Roses')->first()->id;
$Premium_Flowers  = DB::connection('order')->table('store_categories')->where('company_id', $company)->where('store_category_name','Premium Flowers')->first()->id;
$Flowers_N_Cakes  = DB::connection('order')->table('store_categories')->where('company_id', $company)->where('store_category_name','Flowers N Cakes')->first()->id;
$Beer  = DB::connection('order')->table('store_categories')->where('company_id', $company)->where('store_category_name','Beer')->first()->id;
$Whisky  = DB::connection('order')->table('store_categories')->where('company_id', $company)->where('store_category_name','Whisky')->first()->id;
$Brandy  = DB::connection('order')->table('store_categories')->where('company_id', $company)->where('store_category_name','Brandy')->first()->id;
$Tequila  = DB::connection('order')->table('store_categories')->where('company_id', $company)->where('store_category_name','Tequila')->first()->id;
$Rum  = DB::connection('order')->table('store_categories')->where('company_id', $company)->where('store_category_name','Rum')->first()->id;
$Bacardi_Limon  = DB::connection('order')->table('store_categories')->where('company_id', $company)->where('store_category_name','Bacardi Limon')->first()->id;
$Spirits  = DB::connection('order')->table('store_categories')->where('company_id', $company)->where('store_category_name','Spirits')->first()->id;
$Bourbon  = DB::connection('order')->table('store_categories')->where('company_id', $company)->where('store_category_name','Bourbon')->first()->id;
$Beer  = DB::connection('order')->table('store_categories')->where('company_id', $company)->where('store_category_name','Beer')->first()->id;
$Scotch  = DB::connection('order')->table('store_categories')->where('company_id', $company)->where('store_category_name','Scotch')->first()->id;
$Veg  = DB::connection('order')->table('store_categories')->where('company_id', $company)->where('store_category_name','Veg')->first()->id;
$Non_Veg  = DB::connection('order')->table('store_categories')->where('company_id', $company)->where('store_category_name','Non-Veg')->first()->id;
$Veg  = DB::connection('order')->table('store_categories')->where('company_id', $company)->where('store_category_name','Veg')->first()->id;
$Veg  = DB::connection('order')->table('store_categories')->where('company_id', $company)->where('store_category_name','Veg')->first()->id;
$Non_Veg  = DB::connection('order')->table('store_categories')->where('company_id', $company)->where('store_category_name','Non-Veg')->first()->id;
$Non_Veg  = DB::connection('order')->table('store_categories')->where('company_id', $company)->where('store_category_name','Non-Veg')->first()->id;
$Roses  = DB::connection('order')->table('store_categories')->where('company_id', $company)->where('store_category_name','Roses')->first()->id;
$Carnations  = DB::connection('order')->table('store_categories')->where('company_id', $company)->where('store_category_name','Carnations')->first()->id;
$Gerberas  = DB::connection('order')->table('store_categories')->where('company_id', $company)->where('store_category_name','Gerberas')->first()->id;
$Mix_Flowers  = DB::connection('order')->table('store_categories')->where('company_id', $company)->where('store_category_name','Mix Flowers')->first()->id;
$Flowers_By_Colors  = DB::connection('order')->table('store_categories')->where('company_id', $company)->where('store_category_name','Flowers By Colors')->first()->id;
$Flowers_By_Combo  = DB::connection('order')->table('store_categories')->where('company_id', $company)->where('store_category_name','Flowers By Combo')->first()->id;
$Flowers_By_Design  = DB::connection('order')->table('store_categories')->where('company_id', $company)->where('store_category_name','Flowers By Design')->first()->id;
$Flowers_By_Price  = DB::connection('order')->table('store_categories')->where('company_id', $company)->where('store_category_name','Flowers By Price')->first()->id;
$Orchids_  = DB::connection('order')->table('store_categories')->where('company_id', $company)->where('store_category_name','Orchids')->first()->id;
$Lilies  = DB::connection('order')->table('store_categories')->where('company_id', $company)->where('store_category_name','Lilies')->first()->id;
$Beverages  = DB::connection('order')->table('store_categories')->where('company_id', $company)->where('store_category_name','Beverages')->first()->id;
$Bread_Bakery  = DB::connection('order')->table('store_categories')->where('company_id', $company)->where('store_category_name','Bread/Bakery')->first()->id;
$Staples  = DB::connection('order')->table('store_categories')->where('company_id', $company)->where('store_category_name','Staples')->first()->id;
$Dairy  = DB::connection('order')->table('store_categories')->where('company_id', $company)->where('store_category_name','Dairy')->first()->id;
$Dry_Baking_Goods  = DB::connection('order')->table('store_categories')->where('company_id', $company)->where('store_category_name','Dry/Baking Goods')->first()->id;
$Chocolates__Sweets  = DB::connection('order')->table('store_categories')->where('company_id', $company)->where('store_category_name','Chocolates & Sweets')->first()->id;
$Soft_Drinks  = DB::connection('order')->table('store_categories')->where('company_id', $company)->where('store_category_name','Soft Drinks')->first()->id;
$Packaged_food  = DB::connection('order')->table('store_categories')->where('company_id', $company)->where('store_category_name','Packaged food')->first()->id;
$Dals_and_Pulses  = DB::connection('order')->table('store_categories')->where('company_id', $company)->where('store_category_name','Dals and Pulses')->first()->id;
$Pickles__Chutney  = DB::connection('order')->table('store_categories')->where('company_id', $company)->where('store_category_name','Pickles & Chutney')->first()->id;
$Ketchups__Spreads  = DB::connection('order')->table('store_categories')->where('company_id', $company)->where('store_category_name','Ketchups & Spreads')->first()->id;
$Masalas__Spices  = DB::connection('order')->table('store_categories')->where('company_id', $company)->where('store_category_name','Masalas & Spices')->first()->id;
$Dry_Fruits_Nuts__Seeds  = DB::connection('order')->table('store_categories')->where('company_id', $company)->where('store_category_name','Dry Fruits, Nuts & Seeds')->first()->id;
$Health_Drink_Mix  = DB::connection('order')->table('store_categories')->where('company_id', $company)->where('store_category_name','Health Drink Mix')->first()->id;
$Snacks  = DB::connection('order')->table('store_categories')->where('company_id', $company)->where('store_category_name','Snacks')->first()->id; 

        

        DB::connection('order')->table('store_items')->insert([
            ['store_id' => $Thalapakatti,'item_name' =>'Chicken 65','item_description' =>'chicken 65' ,'picture' => url('/').'/images/order/items/chicken_65.png','store_category_id' =>'Non_Vegetarian','is_veg' =>'Non Veg','item_price' =>'100.00','item_discount' =>'10.00','item_discount_type' =>'PERCENTAGE','is_addon' =>'0','status' =>'1','company_id' => $company],
['store_id' => $KFC_Demo,'item_name' =>'Mexican Shawarma','item_description' =>'Delicious!!' ,'picture' => url('/').'/images/order/items/mexican_shawarma.png','store_category_id' =>'Non_Vegetarian','is_veg' =>'Non Veg','item_price' =>'100.00','item_discount' =>'5.00','item_discount_type' =>'PERCENTAGE','is_addon' =>'0','status' =>'1','company_id' => $company],
['store_id' => $SeaShell,'item_name' =>'Chicken Fried Rice','item_description' =>'Delicious!!' ,'picture' => url('/').'/images/order/items/chicken_fried_rice.png','store_category_id' =>'Burger','is_veg' =>'Non Veg','item_price' =>'20.00','item_discount' =>'5.00','item_discount_type' =>'PERCENTAGE','is_addon' =>'0','status' =>'1','company_id' => $company],
['store_id' => $Lassi_Shop,'item_name' =>'Mango Juice','item_description' =>'Yummy!!' ,'picture' => url('/').'/images/order/items/mango_juice.png','store_category_id' =>'Vegetarian','is_veg' =>'Pure Veg','item_price' =>'12.00','item_discount' =>'12.00','item_discount_type' =>'PERCENTAGE','is_addon' =>'0','status' =>'1','company_id' => $company],
['store_id' => $Thalapakatti,'item_name' =>'Chicken Soup','item_description' =>'Delicious!!' ,'picture' => url('/').'/images/order/items/chicken_soup.png','store_category_id' =>'Non_Vegetarian','is_veg' =>'Non Veg','item_price' =>'12.00','item_discount' =>'4.00','item_discount_type' =>'PERCENTAGE','is_addon' =>'0','status' =>'1','company_id' => $company],
['store_id' => $Thalapakatti,'item_name' =>'Chicken Briyani','item_description' =>'Yummy!!' ,'picture' => url('/').'/images/order/items/chicken_briyani.png','store_category_id' =>'Non_Vegetarian','is_veg' =>'Non Veg','item_price' =>'150.00','item_discount' =>'2.00','item_discount_type' =>'PERCENTAGE','is_addon' =>'0','status' =>'1','company_id' => $company],
['store_id' => $Lassi_Shop,'item_name' =>'Vanilla Milkshake','item_description' =>'Yummy!!' ,'picture' => url('/').'/images/order/items/vanilla_milkshake.png','store_category_id' =>'Vegetarian','is_veg' =>'Pure Veg','item_price' =>'100.00','item_discount' =>'5.00','item_discount_type' =>'PERCENTAGE','is_addon' =>'0','status' =>'1','company_id' => $company],
['store_id' => $Lassi_Shop,'item_name' =>'Sweet Lassi','item_description' =>'Yummy!!' ,'picture' => url('/').'/images/order/items/sweet_lassi.png','store_category_id' =>'Vegetarian','is_veg' =>'Pure Veg','item_price' =>'102.00','item_discount' =>'4.00','item_discount_type' =>'PERCENTAGE','is_addon' =>'0','status' =>'1','company_id' => $company],
['store_id' => $Thalapakatti,'item_name' =>'Egg Briyani','item_description' =>'Yummy!!' ,'picture' => url('/').'/images/order/items/egg_briyani.png','store_category_id' =>'Non_Vegetarian','is_veg' =>'Non Veg','item_price' =>'150.00','item_discount' =>'5.00','item_discount_type' =>'PERCENTAGE','is_addon' =>'0','status' =>'1','company_id' => $company],
['store_id' => $Thalapakatti,'item_name' =>'Fish Fry','item_description' =>'Delicious!!' ,'picture' => url('/').'/images/order/items/fish_fry.png','store_category_id' =>'Non_Vegetarian','is_veg' =>'Non Veg','item_price' =>'200.00','item_discount' =>'5.00','item_discount_type' =>'PERCENTAGE','is_addon' =>'0','status' =>'1','company_id' => $company],
['store_id' => $Thalapakatti,'item_name' =>'Grill Chicken','item_description' =>'Delicious!!' ,'picture' => url('/').'/images/order/items/grill_chicken.png','store_category_id' =>'Non_Vegetarian','is_veg' =>'Non Veg','item_price' =>'100.00','item_discount' =>'5.00','item_discount_type' =>'PERCENTAGE','is_addon' =>'0','status' =>'1','company_id' => $company],
['store_id' => $Thalapakatti,'item_name' =>'Prawn Fry','item_description' =>'Yummy!!' ,'picture' => url('/').'/images/order/items/prawn_fry.png','store_category_id' =>'Non_Vegetarian','is_veg' =>'Non Veg','item_price' =>'200.00','item_discount' =>'5.00','item_discount_type' =>'PERCENTAGE','is_addon' =>'0','status' =>'1','company_id' => $company],
['store_id' => $Thalapakatti,'item_name' =>'Veg Soup','item_description' =>'Yummy!!' ,'picture' => url('/').'/images/order/items/veg_soup.png','store_category_id' =>'Veg','is_veg' =>'Pure Veg','item_price' =>'100.00','item_discount' =>'2.00','item_discount_type' =>'PERCENTAGE','is_addon' =>'0','status' =>'1','company_id' => $company],
['store_id' => $KFC_Demo,'item_name' =>'Chicken Burger','item_description' =>'Yummy!!' ,'picture' => url('/').'/images/order/items/chicken_burger.png','store_category_id' =>'Non_Vegetarian','is_veg' =>'Non Veg','item_price' =>'100.00','item_discount' =>'200.00','item_discount_type' =>'PERCENTAGE','is_addon' =>'0','status' =>'1','company_id' => $company],
['store_id' => $KFC_Demo,'item_name' =>'Combo Pack','item_description' =>'' ,'picture' => url('/').'/images/order/items/combo_pack.png','store_category_id' =>'Non_Vegetarian','is_veg' =>'Non Veg','item_price' =>'200.00','item_discount' =>'4.00','item_discount_type' =>'PERCENTAGE','is_addon' =>'0','status' =>'1','company_id' => $company],
['store_id' => $KFC_Demo,'item_name' =>'French Fries','item_description' =>'Delicious!!' ,'picture' => url('/').'/images/order/items/french_fries.png','store_category_id' =>'Non_Vegetarian','is_veg' =>'Pure Veg','item_price' =>'50.00','item_discount' =>'4.00','item_discount_type' =>'PERCENTAGE','is_addon' =>'0','status' =>'1','company_id' => $company],
['store_id' => $KFC_Demo,'item_name' =>'Nuggets','item_description' =>'Delicious!!' ,'picture' => url('/').'/images/order/items/nuggets.png','store_category_id' =>'Non_Vegetarian','is_veg' =>'Non Veg','item_price' =>'100.00','item_discount' =>'0.00','item_discount_type' =>'PERCENTAGE','is_addon' =>'0','status' =>'1','company_id' => $company],
['store_id' => $KFC_Demo,'item_name' =>'Pop-corn Chicken','item_description' =>'Yummy!!' ,'picture' => url('/').'/images/order/items/pop-corn_chicken.png','store_category_id' =>'Non_Vegetarian','is_veg' =>'Non Veg','item_price' =>'200.00','item_discount' =>'0.00','item_discount_type' =>'PERCENTAGE','is_addon' =>'0','status' =>'1','company_id' => $company],
['store_id' => $Lassi_Shop,'item_name' =>'Strawberry Shake','item_description' =>'Yummy!!' ,'picture' => url('/').'/images/order/items/strawberry_shake.png','store_category_id' =>'Vegetarian','is_veg' =>'Pure Veg','item_price' =>'200.00','item_discount' =>'0.00','item_discount_type' =>'PERCENTAGE','is_addon' =>'0','status' =>'1','company_id' => $company],
['store_id' => $Lassi_Shop,'item_name' =>'Butterscotch Shake','item_description' =>'Yummy!!' ,'picture' => url('/').'/images/order/items/butterscotch_shake.png','store_category_id' =>'Vegetarian','is_veg' =>'Pure Veg','item_price' =>'200.00','item_discount' =>'0.00','item_discount_type' =>'PERCENTAGE','is_addon' =>'0','status' =>'1','company_id' => $company],
['store_id' => $SeaShell,'item_name' =>'Chicken Noodles','item_description' =>'Yummy!!' ,'picture' => url('/').'/images/order/items/chicken_noodles.png','store_category_id' =>'Burger','is_veg' =>'Non Veg','item_price' =>'200.00','item_discount' =>'5.00','item_discount_type' =>'PERCENTAGE','is_addon' =>'0','status' =>'1','company_id' => $company],
['store_id' => $SeaShell,'item_name' =>'Prawn Fry','item_description' =>'Yummy!!' ,'picture' => url('/').'/images/order/items/prawn_fry.png','store_category_id' =>'Burger','is_veg' =>'Non Veg','item_price' =>'100.00','item_discount' =>'4.00','item_discount_type' =>'PERCENTAGE','is_addon' =>'0','status' =>'1','company_id' => $company],
['store_id' => $SeaShell,'item_name' =>'Mutton Briyani','item_description' =>'Yummy!!' ,'picture' => url('/').'/images/order/items/mutton_briyani.png','store_category_id' =>'Burger','is_veg' =>'Non Veg','item_price' =>'200.00','item_discount' =>'4.00','item_discount_type' =>'PERCENTAGE','is_addon' =>'0','status' =>'1','company_id' => $company],
['store_id' => $AlbertSons,'item_name' =>'Lacroix Drinks','item_description' =>'Drinks' ,'picture' => url('/').'/images/order/items/lacroix_drinks.png','store_category_id' =>'Beverages','is_veg' =>'Pure Veg','item_price' =>'100.00','item_discount' =>'5.00','item_discount_type' =>'PERCENTAGE','is_addon' =>'0','status' =>'1','company_id' => $company],
['store_id' => $AlbertSons,'item_name' =>'Cocacola','item_description' =>'Drinks' ,'picture' => url('/').'/images/order/items/cocacola.png','store_category_id' =>'Beverages','is_veg' =>'Pure Veg','item_price' =>'50.00','item_discount' =>'1.00','item_discount_type' =>'PERCENTAGE','is_addon' =>'0','status' =>'1','company_id' => $company],
['store_id' => $AlbertSons,'item_name' =>'Cheerios','item_description' =>'Cereal' ,'picture' => url('/').'/images/order/items/cheerios_.png','store_category_id' =>'Breakfast_and_cereal','is_veg' =>'Pure Veg','item_price' =>'200.00','item_discount' =>'3.00','item_discount_type' =>'PERCENTAGE','is_addon' =>'0','status' =>'1','company_id' => $company],
['store_id' => $AlbertSons,'item_name' =>'Pop Tarts','item_description' =>'Poptarts' ,'picture' => url('/').'/images/order/items/pop_tarts.png','store_category_id' =>'Breakfast_and_cereal','is_veg' =>'Pure Veg','item_price' =>'36.00','item_discount' =>'5.00','item_discount_type' =>'PERCENTAGE','is_addon' =>'0','status' =>'1','company_id' => $company],
['store_id' => $AlbertSons,'item_name' =>'Belvita','item_description' =>'Belvita' ,'picture' => url('/').'/images/order/items/belvita.png','store_category_id' =>'Breakfast_and_cereal','is_veg' =>'Pure Veg','item_price' =>'200.00','item_discount' =>'5.00','item_discount_type' =>'PERCENTAGE','is_addon' =>'0','status' =>'1','company_id' => $company],
['store_id' => $AlbertSons,'item_name' =>'Quaker Oats','item_description' =>'Quaker Oats' ,'picture' => url('/').'/images/order/items/quaker_oats.png','store_category_id' =>'Breakfast_and_cereal','is_veg' =>'Pure Veg','item_price' =>'200.00','item_discount' =>'5.00','item_discount_type' =>'PERCENTAGE','is_addon' =>'0','status' =>'1','company_id' => $company],
['store_id' => $AlbertSons,'item_name' =>'Tupils Bouquet','item_description' =>'Bouquet' ,'picture' => url('/').'/images/order/items/tupils_bouquet.png','store_category_id' =>'Flowers','is_veg' =>'Pure Veg','item_price' =>'50.00','item_discount' =>'5.00','item_discount_type' =>'PERCENTAGE','is_addon' =>'0','status' =>'1','company_id' => $company],
['store_id' => $AlbertSons,'item_name' =>'Red Rose Bouquet','item_description' =>'Red Roses' ,'picture' => url('/').'/images/order/items/red_rose_bouquet.png','store_category_id' =>'Flowers','is_veg' =>'Pure Veg','item_price' =>'100.00','item_discount' =>'5.00','item_discount_type' =>'PERCENTAGE','is_addon' =>'0','status' =>'1','company_id' => $company],
['store_id' => $AlbertSons,'item_name' =>'Bunch Bouquet','item_description' =>'Bouquet' ,'picture' => url('/').'/images/order/items/bunch_bouquet.png','store_category_id' =>'Flowers','is_veg' =>'Pure Veg','item_price' =>'100.00','item_discount' =>'4.00','item_discount_type' =>'PERCENTAGE','is_addon' =>'0','status' =>'1','company_id' => $company],
['store_id' => $Aldi,'item_name' =>'Marshmallow','item_description' =>'Marshmallow' ,'picture' => url('/').'/images/order/items/marshmallow.png','store_category_id' =>'Diary','is_veg' =>'Pure Veg','item_price' =>'50.00','item_discount' =>'5.00','item_discount_type' =>'PERCENTAGE','is_addon' =>'0','status' =>'1','company_id' => $company],
['store_id' => $Aldi,'item_name' =>'American SIngles','item_description' =>'American SIngles' ,'picture' => url('/').'/images/order/items/american_singles.png','store_category_id' =>'Diary','is_veg' =>'Pure Veg','item_price' =>'100.00','item_discount' =>'3.00','item_discount_type' =>'PERCENTAGE','is_addon' =>'0','status' =>'1','company_id' => $company],
['store_id' => $Aldi,'item_name' =>'Cheese','item_description' =>'Cheese' ,'picture' => url('/').'/images/order/items/cheese.png','store_category_id' =>'Diary','is_veg' =>'Pure Veg','item_price' =>'100.00','item_discount' =>'2.00','item_discount_type' =>'PERCENTAGE','is_addon' =>'0','status' =>'1','company_id' => $company],
['store_id' => $Aldi,'item_name' =>'Boneless Chicken','item_description' =>'Boneless Chicken' ,'picture' => url('/').'/images/order/items/boneless_chicken.png','store_category_id' =>'Meat','is_veg' =>'Non Veg','item_price' =>'400.00','item_discount' =>'3.00','item_discount_type' =>'PERCENTAGE','is_addon' =>'0','status' =>'1','company_id' => $company],
['store_id' => $Aldi,'item_name' =>'Meat','item_description' =>'Meat' ,'picture' => url('/').'/images/order/items/meat.png','store_category_id' =>'Meat','is_veg' =>'Non Veg','item_price' =>'100.00','item_discount' =>'3.00','item_discount_type' =>'PERCENTAGE','is_addon' =>'0','status' =>'1','company_id' => $company],
['store_id' => $Aldi,'item_name' =>'Tuna Salad','item_description' =>'Tuna Salad' ,'picture' => url('/').'/images/order/items/tuna_salad.png','store_category_id' =>'Pantry','is_veg' =>'Non Veg','item_price' =>'200.00','item_discount' =>'3.00','item_discount_type' =>'PERCENTAGE','is_addon' =>'0','status' =>'1','company_id' => $company],
['store_id' => $Aldi,'item_name' =>'Ranch','item_description' =>'Ranch' ,'picture' => url('/').'/images/order/items/ranch.png','store_category_id' =>'Pantry','is_veg' =>'Non Veg','item_price' =>'100.00','item_discount' =>'2.00','item_discount_type' =>'PERCENTAGE','is_addon' =>'0','status' =>'1','company_id' => $company],
['store_id' => $Kroger_Shop,'item_name' =>'Mini Cookies','item_description' =>'Mini Cookies' ,'picture' => url('/').'/images/order/items/mini_cookies.png','store_category_id' =>'Bakery','is_veg' =>'Pure Veg','item_price' =>'200.00','item_discount' =>'3.00','item_discount_type' =>'PERCENTAGE','is_addon' =>'0','status' =>'1','company_id' => $company],
['store_id' => $Kroger_Shop,'item_name' =>'Sugar Cookies','item_description' =>'Sugar Cookies' ,'picture' => url('/').'/images/order/items/sugar_cookies.png','store_category_id' =>'Bakery','is_veg' =>'Pure Veg','item_price' =>'200.00','item_discount' =>'4.00','item_discount_type' =>'PERCENTAGE','is_addon' =>'0','status' =>'1','company_id' => $company],
['store_id' => $Kroger_Shop,'item_name' =>'Strawberry Cake','item_description' =>'Strawberry Cake' ,'picture' => url('/').'/images/order/items/strawberry_cake.png','store_category_id' =>'Bakery','is_veg' =>'Non Veg','item_price' =>'200.00','item_discount' =>'5.00','item_discount_type' =>'PERCENTAGE','is_addon' =>'0','status' =>'1','company_id' => $company],
['store_id' => $Kroger_Shop,'item_name' =>'Bacon','item_description' =>'Bacon' ,'picture' => url('/').'/images/order/items/bacon.png','store_category_id' =>'Frozen','is_veg' =>'Non Veg','item_price' =>'200.00','item_discount' =>'3.00','item_discount_type' =>'PERCENTAGE','is_addon' =>'0','status' =>'1','company_id' => $company],
['store_id' => $Kroger_Shop,'item_name' =>'Vividly Vanilla','item_description' =>'Vividly Vanilla' ,'picture' => url('/').'/images/order/items/vividly_vanilla.png','store_category_id' =>'Frozen','is_veg' =>'Non Veg','item_price' =>'200.00','item_discount' =>'3.00','item_discount_type' =>'PERCENTAGE','is_addon' =>'0','status' =>'1','company_id' => $company],
['store_id' => $Kroger_Shop,'item_name' =>'Air Freshener','item_description' =>'Air Freshener' ,'picture' => url('/').'/images/order/items/air_freshener.png','store_category_id' =>'HouseHold','is_veg' =>'Non Veg','item_price' =>'200.00','item_discount' =>'3.00','item_discount_type' =>'PERCENTAGE','is_addon' =>'0','status' =>'1','company_id' => $company],
['store_id' => $Kroger_Shop,'item_name' =>'Shower Cleaner','item_description' =>'Shower Cleaner' ,'picture' => url('/').'/images/order/items/shower_cleaner.png','store_category_id' =>'HouseHold','is_veg' =>'Non Veg','item_price' =>'200.00','item_discount' =>'2.00','item_discount_type' =>'PERCENTAGE','is_addon' =>'0','status' =>'1','company_id' => $company],
['store_id' => $_Flower,'item_name' =>'Floral Embrace','item_description' =>'Floral Embrace' ,'picture' => url('/').'/images/order/items/floral_embrace.png','store_category_id' =>'Same_Day_Flowers','is_veg' =>'Pure Veg','item_price' =>'100.00','item_discount' =>'3.00','item_discount_type' =>'PERCENTAGE','is_addon' =>'0','status' =>'1','company_id' => $company],
['store_id' => $_Flower,'item_name' =>'Lovely Lavender Medley','item_description' =>'Lovely Lavender Medley' ,'picture' => url('/').'/images/order/items/lovely_lavender_medley.png','store_category_id' =>'Same_Day_Flowers','is_veg' =>'Pure Veg','item_price' =>'100.00','item_discount' =>'2.00','item_discount_type' =>'PERCENTAGE','is_addon' =>'0','status' =>'1','company_id' => $company],
['store_id' => $_Flower,'item_name' =>'Blooming Love','item_description' =>'Blooming Love' ,'picture' => url('/').'/images/order/items/blooming_love.png','store_category_id' =>'Same_Day_Flowers','is_veg' =>'Pure Veg','item_price' =>'100.00','item_discount' =>'2.00','item_discount_type' =>'PERCENTAGE','is_addon' =>'0','status' =>'1','company_id' => $company],
['store_id' => $_Flower,'item_name' =>'Wonderful Wishes Bouquet','item_description' =>'Wonderful Wishes Bouquet' ,'picture' => url('/').'/images/order/items/wonderful_wishes_bouquet.png','store_category_id' =>'Birthday','is_veg' =>'Pure Veg','item_price' =>'200.00','item_discount' =>'3.00','item_discount_type' =>'PERCENTAGE','is_addon' =>'0','status' =>'1','company_id' => $company],
['store_id' => $_Flower,'item_name' =>'Sassy nâ€™ Sweet','item_description' =>'Sassy nâ€™ Sweet' ,'picture' => url('/').'/images/order/items/sassy_nâ€™_sweet.png','store_category_id' =>'Birthday','is_veg' =>'Pure Veg','item_price' =>'200.00','item_discount' =>'2.00','item_discount_type' =>'PERCENTAGE','is_addon' =>'0','status' =>'1','company_id' => $company],
['store_id' => $_Flower,'item_name' =>'Assorted Tulips','item_description' =>'Assorted Tulips' ,'picture' => url('/').'/images/order/items/assorted_tulips.png','store_category_id' =>'Birthday','is_veg' =>'Pure Veg','item_price' =>'200.00','item_discount' =>'2.00','item_discount_type' =>'PERCENTAGE','is_addon' =>'0','status' =>'1','company_id' => $company],
['store_id' => $_Flower,'item_name' =>'Healing Tears Blue & White','item_description' =>'Healing Tears Blue & White' ,'picture' => url('/').'/images/order/items/healing_tears_blue_&_white.png','store_category_id' =>'Occasions','is_veg' =>'Pure Veg','item_price' =>'200.00','item_discount' =>'2.00','item_discount_type' =>'PERCENTAGE','is_addon' =>'0','status' =>'1','company_id' => $company],
['store_id' => $_Flower,'item_name' =>'Stunning Red Rose & Calla Lily Bouquet','item_description' =>'Stunning Red Rose & Calla Lily Bouquet' ,'picture' => url('/').'/images/order/items/stunning_red_rose_&_calla_lily_bouquet.png','store_category_id' =>'Occasions','is_veg' =>'Pure Veg','item_price' =>'200.00','item_discount' =>'2.00','item_discount_type' =>'PERCENTAGE','is_addon' =>'0','status' =>'1','company_id' => $company],
['store_id' => $Chowking_nigeria,'item_name' =>'Chow King Fried Rice','item_description' =>'10' ,'picture' => url('/').'/images/order/items/chow_king_fried_rice.png','store_category_id' =>'Rice','is_veg' =>'Non Veg','item_price' =>'1000.00','item_discount' =>'10.00','item_discount_type' =>'PERCENTAGE','is_addon' =>'0','status' =>'1','company_id' => $company],
['store_id' => $MOS_Burger,'item_name' =>'Krusty Burger','item_description' =>'The fictional Simpsons hangout was so popular, it became a real-life restaurant in 2013, when Universal Studios Orlando opened a Simpsons theme park. Ironically, menu staples like the Clogger Burger and the Mother Nature Burger' ,'picture' => url('/').'/images/order/items/krusty_burger.png','store_category_id' =>'Veg','is_veg' =>'Pure Veg','item_price' =>'280.00','item_discount' =>'2.00','item_discount_type' =>'PERCENTAGE','is_addon' =>'0','status' =>'1','company_id' => $company],
['store_id' => $MOS_Burger,'item_name' =>'Varsity Burger','item_description' =>'The ordering lingo for this Atlanta staple, which debuted in 1928, is almost as delicious as the burger itself: you get it â€œall the wayâ€ in lieu of â€œwith onions,â€ and â€œwalk a steakâ€ replaces â€œto-go.â€' ,'picture' => url('/').'/images/order/items/varsity_burger.png','store_category_id' =>'Veg','is_veg' =>'Pure Veg','item_price' =>'250.00','item_discount' =>'5.00','item_discount_type' =>'PERCENTAGE','is_addon' =>'0','status' =>'1','company_id' => $company],
['store_id' => $MOS_Burger,'item_name' =>'Umami Burger','item_description' =>'It  meant to taste like, well, umami (a savory taste embodied in MSG), incorporating such toppings as soy-roasted tomatoes, parmesan crisps and pickled ginger.' ,'picture' => url('/').'/images/order/items/umami_burger.png','store_category_id' =>'Veg','is_veg' =>'Pure Veg','item_price' =>'100.00','item_discount' =>'3.00','item_discount_type' =>'PERCENTAGE','is_addon' =>'0','status' =>'1','company_id' => $company],
['store_id' => $MOS_Burger,'item_name' =>'Shack Burger','item_description' =>' The first burger to start a food craze, inspiring hordes of eaters to wait in lines that stretched throughout New Yorkâ€™s Madison Square Park.' ,'picture' => url('/').'/images/order/items/shack_burger.png','store_category_id' =>'Veg','is_veg' =>'Pure Veg','item_price' =>'5.00','item_discount' =>'5.00','item_discount_type' =>'PERCENTAGE','is_addon' =>'0','status' =>'1','company_id' => $company],
['store_id' => $MOS_Burger,'item_name' =>'Burger King Whopper','item_description' =>'Fast food industryâ€™s first gimmick burgerâ€”developed as a premium alternative to McDonaldâ€™s, Wendyâ€™s and others.' ,'picture' => url('/').'/images/order/items/burger_king_whopper.png','store_category_id' =>'Veg','is_veg' =>'Pure Veg','item_price' =>'100.00','item_discount' =>'5.00','item_discount_type' =>'PERCENTAGE','is_addon' =>'0','status' =>'1','company_id' => $company],
['store_id' => $MOS_Burger,'item_name' =>'The 21 Burger','item_description' =>'When the 21 Club introduced its gourmet burger in the late 1940s or early 1950s, New Yorkers were shocked that an upper-class establishment would offer something as lowly as the burger' ,'picture' => url('/').'/images/order/items/the_21_burger.png','store_category_id' =>'Veg','is_veg' =>'Pure Veg','item_price' =>'100.00','item_discount' =>'5.00','item_discount_type' =>'PERCENTAGE','is_addon' =>'0','status' =>'1','company_id' => $company],
['store_id' => $MOS_Burger,'item_name' =>'In-N-Out Burger','item_description' =>'Whereas McDonaldâ€™s focused on fast, In-N-Out focused on foodâ€”its signature burger, which debuted in 1948, was made from locally sourced ground beef and fresh vegetables' ,'picture' => url('/').'/images/order/items/in-n-out_burger.png','store_category_id' =>'Veg','is_veg' =>'Pure Veg','item_price' =>'100.00','item_discount' =>'5.00','item_discount_type' =>'PERCENTAGE','is_addon' =>'0','status' =>'1','company_id' => $company],
['store_id' => $MOS_Burger,'item_name' =>'White Castle Slider','item_description' =>'White Castle had 10 U.S. locations. But more importantly, the restaurantâ€™s emphasis on cleanlinessâ€”facilities were white and customers could watch their burger meat being ground through a window' ,'picture' => url('/').'/images/order/items/white_castle_slider.png','store_category_id' =>'Veg','is_veg' =>'Pure Veg','item_price' =>'350.00','item_discount' =>'100.00','item_discount_type' =>'PERCENTAGE','is_addon' =>'0','status' =>'1','company_id' => $company],
['store_id' => $MOS_Burger,'item_name' =>'Gardenburger','item_description' =>'The original veggie burger was invented in 1981 atâ€”go figureâ€”the Gardenhouse, an Oregon vegetarian restaurant, and it consisted mainly of leftover vegetables and grains' ,'picture' => url('/').'/images/order/items/gardenburger.png','store_category_id' =>'Veg','is_veg' =>'Pure Veg','item_price' =>'350.00','item_discount' =>'5.00','item_discount_type' =>'PERCENTAGE','is_addon' =>'0','status' =>'1','company_id' => $company],
['store_id' => $MOS_Burger,'item_name' =>'Quadruple Bypass Burger','item_description' =>'The burger became an exemplar of the more-is-more burger culture, preceding a series of other gluttonous dishes including Paula Deenâ€™s doughnut-encased Ladyâ€™s Brunch Burger.' ,'picture' => url('/').'/images/order/items/quadruple_bypass_burger.png','store_category_id' =>'Veg','is_veg' =>'Pure Veg','item_price' =>'250.00','item_discount' =>'5.00','item_discount_type' =>'PERCENTAGE','is_addon' =>'0','status' =>'1','company_id' => $company],
['store_id' => $Thalapakatti,'item_name' =>'Mughal Briyani','item_description' =>'Biryani may soon be declared as the national dish in India for the fact that it is a dish which beyond cultures is a favourite among most. How it arrived in India has a lot of legendary stories.' ,'picture' => url('/').'/images/order/items/mughal_briyani.png','store_category_id' =>'Non_Vegetarian','is_veg' =>'Non Veg','item_price' =>'100.00','item_discount' =>'5.00','item_discount_type' =>'PERCENTAGE','is_addon' =>'0','status' =>'1','company_id' => $company],
['store_id' => $Thalapakatti,'item_name' =>'Hyderabadi Biryani','item_description' =>'When we think of biryani, Hyderabadi Biryani is the first that comes to oneâ€™s mind. It was initially conceived as a dish under Asaf Jaha I, the appointed Governor of Deccan by Aurangzeb' ,'picture' => url('/').'/images/order/items/hyderabadi_biryani.png','store_category_id' =>'Non_Vegetarian','is_veg' =>'Non Veg','item_price' =>'250.00','item_discount' =>'5.00','item_discount_type' =>'PERCENTAGE','is_addon' =>'0','status' =>'1','company_id' => $company],
['store_id' => $KFC_Demo,'item_name' =>'SCOFF-EE CUP','item_description' =>'The way you see the Britt enjoy the taste of the "Scoff-ee Cup" menu should say a lot to you already. It\'s a delicious recipe that you should surely try at least once before you see your deathbed.' ,'picture' => url('/').'/images/order/items/scoff-ee_cup.png','store_category_id' =>'Non_Vegetarian','is_veg' =>'Pure Veg','item_price' =>'250.00','item_discount' =>'5.00','item_discount_type' =>'PERCENTAGE','is_addon' =>'0','status' =>'1','company_id' => $company],
['store_id' => $KFC_Demo,'item_name' =>'DEEP-FRIED CORN SOUP','item_description' =>'The deep-fried corn soup is a perfect combination of delicious and unique. Thatâ€™s why the Japanese can\'t get over it.' ,'picture' => url('/').'/images/order/items/deep-fried_corn_soup.png','store_category_id' =>'Non_Vegetarian','is_veg' =>'Pure Veg','item_price' =>'100.00','item_discount' =>'5.00','item_discount_type' =>'PERCENTAGE','is_addon' =>'0','status' =>'1','company_id' => $company],
['store_id' => $KFC_Demo,'item_name' =>'VEGETABLE STRIPS','item_description' =>'The vegetable strips caused the chicken to be ditched in the dumps because the deep-fried batter found its way around vegetables' ,'picture' => url('/').'/images/order/items/vegetable_strips.png','store_category_id' =>'Non_Vegetarian','is_veg' =>'Non Veg','item_price' =>'100.00','item_discount' =>'5.00','item_discount_type' =>'PERCENTAGE','is_addon' =>'0','status' =>'1','company_id' => $company],
['store_id' => $KFC_Demo,'item_name' =>'DIPPING FRIES','item_description' =>'The dipping fries are hollowed-out fries that have the shape of fried potato skin. The reason why the fries are hollowed-out is to make sure all the dip you want to stay firm on the snack.' ,'picture' => url('/').'/images/order/items/dipping_fries.png','store_category_id' =>'Non_Vegetarian','is_veg' =>'Pure Veg','item_price' =>'450.00','item_discount' =>'11.00','item_discount_type' =>'PERCENTAGE','is_addon' =>'0','status' =>'1','company_id' => $company],
['store_id' => $KFC_Demo,'item_name' =>'DIPPING FRIES','item_description' =>'The dipping fries are hollowed-out fries that have the shape of fried potato skin. The reason why the fries are hollowed-out is to make sure all the dip you want to stay firm on the snack.' ,'picture' => url('/').'/images/order/items/dipping_fries.png','store_category_id' =>'Non_Vegetarian','is_veg' =>'Pure Veg','item_price' =>'450.00','item_discount' =>'11.00','item_discount_type' =>'PERCENTAGE','is_addon' =>'0','status' =>'1','company_id' => $company],
['store_id' => $Lassi_Shop,'item_name' =>'Chilled Darjeeling First Flush with Mango','item_description' =>'Add iced water (sans the ice) to the tea to make enough for 4 glasses and also to dilute the tea which would otherwise be very intensely flavoured.' ,'picture' => url('/').'/images/order/items/chilled_darjeeling_first_flush_with_mango.png','store_category_id' =>'Vegetarian','is_veg' =>'Pure Veg','item_price' =>'75.00','item_discount' =>'5.00','item_discount_type' =>'PERCENTAGE','is_addon' =>'0','status' =>'1','company_id' => $company],
['store_id' => $Lassi_Shop,'item_name' =>'Milk Thandai Recipe','item_description' =>'For a larger batch of the spice mix, dry grind and keep in an airtight container, refrigerated for a few days. You can also alter the quantities to suit your personal taste and preference.' ,'picture' => url('/').'/images/order/items/milk_thandai_recipe.png','store_category_id' =>'Vegetarian','is_veg' =>'Pure Veg','item_price' =>'45.00','item_discount' =>'5.00','item_discount_type' =>'PERCENTAGE','is_addon' =>'0','status' =>'1','company_id' => $company],
['store_id' => $Lassi_Shop,'item_name' =>'Spinach Dip Recipe','item_description' =>'Add nutmeg and salt to taste. Let the mixture cool down and put in blender and grind for desired consistency.' ,'picture' => url('/').'/images/order/items/spinach_dip_recipe.png','store_category_id' =>'Vegetarian','is_veg' =>'Pure Veg','item_price' =>'50.00','item_discount' =>'4.00','item_discount_type' =>'PERCENTAGE','is_addon' =>'0','status' =>'1','company_id' => $company],
['store_id' => $Lassi_Shop,'item_name' =>'Irish Coffee','item_description' =>'Whip the cream until the bubbles disappear and it has just started to thicken and form ribbons underneath the whisk. Put back in the refrigerator.' ,'picture' => url('/').'/images/order/items/irish_coffee.png','store_category_id' =>'Vegetarian','is_veg' =>'Pure Veg','item_price' =>'35.00','item_discount' =>'5.00','item_discount_type' =>'PERCENTAGE','is_addon' =>'0','status' =>'1','company_id' => $company],
['store_id' => $Lassi_Shop,'item_name' =>'Fruit Infused Tea Recipe','item_description' =>'Test' ,'picture' => url('/').'/images/order/items/fruit_infused_tea_recipe.png','store_category_id' =>'Vegetarian','is_veg' =>'Pure Veg','item_price' =>'10.00','item_discount' =>'5.00','item_discount_type' =>'PERCENTAGE','is_addon' =>'0','status' =>'1','company_id' => $company],
['store_id' => $SeaShell,'item_name' =>'Portugese Fish Stew Recipe','item_description' =>'This Portugese fish stew is an easy and simple recipe to prepare for a brunch or light side dish for dinner. Potatoes, fish fillet, shrimps, few veggies along with white wine and spices come together to form this delicious stew that you can serve with coo' ,'picture' => url('/').'/images/order/items/portugese_fish_stew_recipe.png','store_category_id' =>'Burger','is_veg' =>'Pure Veg','item_price' =>'350.00','item_discount' =>'5.00','item_discount_type' =>'PERCENTAGE','is_addon' =>'0','status' =>'1','company_id' => $company],
['store_id' => $Ferns_and_Petals,'item_name' =>'Vivid-Red Rose Bouquet','item_description' =>'Roses' ,'picture' => url('/').'/images/order/items/vivid-red_rose_bouquet.png','store_category_id' =>'Roses','is_veg' =>'Pure Veg','item_price' =>'200.00','item_discount' =>'2.00','item_discount_type' =>'PERCENTAGE','is_addon' =>'0','status' =>'1','company_id' => $company],
['store_id' => $Ferns_and_Petals,'item_name' =>'Endearing 8 Pink Roses Bouquet','item_description' =>'Roses' ,'picture' => url('/').'/images/order/items/endearing_8_pink_roses_bouquet.png','store_category_id' =>'Roses','is_veg' =>'Pure Veg','item_price' =>'200.00','item_discount' =>'3.00','item_discount_type' =>'PERCENTAGE','is_addon' =>'0','status' =>'1','company_id' => $company],
['store_id' => $Ferns_and_Petals,'item_name' =>'Pristine White Roses Bunch','item_description' =>'Roses' ,'picture' => url('/').'/images/order/items/pristine_white_roses_bunch.png','store_category_id' =>'Roses','is_veg' =>'Pure Veg','item_price' =>'200.00','item_discount' =>'2.00','item_discount_type' =>'PERCENTAGE','is_addon' =>'0','status' =>'1','company_id' => $company],
['store_id' => $Ferns_and_Petals,'item_name' =>'Royal- Forever Blue Rose in Velvet Box','item_description' =>'Roses' ,'picture' => url('/').'/images/order/items/royal-_forever_blue_rose_in_velvet_box.png','store_category_id' =>'Roses','is_veg' =>'Pure Veg','item_price' =>'496.00','item_discount' =>'2.00','item_discount_type' =>'PERCENTAGE','is_addon' =>'0','status' =>'1','company_id' => $company],
['store_id' => $Bonchon_Chicken,'item_name' =>'Korean Fried Chicken','item_description' =>'This dish was traditionally eaten on the eve of the lunar new year as the people at that time felt that they had to get rid of all of their leftover side dishes before the new year. It is listed at number 40 on the Worldâ€™s 50 Most Delicious Food Readers' ,'picture' => url('/').'/images/order/items/korean_fried_chicken.png','store_category_id' =>'Non_Veg','is_veg' =>'Non Veg','item_price' =>'95.00','item_discount' =>'0.00','item_discount_type' =>'PERCENTAGE','is_addon' =>'0','status' =>'1','company_id' => $company],
['store_id' => $Ferns_and_Petals,'item_name' =>'Roses-orchids-vase-arrangement','item_description' =>'roses-orchids-vase-arrangement' ,'picture' => url('/').'/images/order/items/roses-orchids-vase-arrangement.png','store_category_id' =>'Premium_Flowers','is_veg' =>'Pure Veg','item_price' =>'1500.00','item_discount' =>'2.00','item_discount_type' =>'PERCENTAGE','is_addon' =>'0','status' =>'1','company_id' => $company],
['store_id' => $Ferns_and_Petals,'item_name' =>'Beautiful Box Of Roses','item_description' =>'Beautiful Box Of Roses' ,'picture' => url('/').'/images/order/items/beautiful_box_of_roses.png','store_category_id' =>'Premium_Flowers','is_veg' =>'Pure Veg','item_price' =>'200.00','item_discount' =>'2.00','item_discount_type' =>'PERCENTAGE','is_addon' =>'0','status' =>'1','company_id' => $company],
['store_id' => $Bonchon_Chicken,'item_name' =>'Korean Fried Chicken Wings','item_description' =>'double-fried with one of two secret sauces. Despite Bonchonâ€™s growing presence around the world, our name ensures we never lose sight of our roots.' ,'picture' => url('/').'/images/order/items/korean_fried_chicken_wings.png','store_category_id' =>'Non_Veg','is_veg' =>'Non Veg','item_price' =>'100.00','item_discount' =>'0.00','item_discount_type' =>'PERCENTAGE','is_addon' =>'0','status' =>'1','company_id' => $company],
['store_id' => $Ferns_and_Petals,'item_name' =>'Symphony Of Orange Roses','item_description' =>'Symphony Of Orange Roses' ,'picture' => url('/').'/images/order/items/symphony_of_orange_roses.png','store_category_id' =>'Premium_Flowers','is_veg' =>'Pure Veg','item_price' =>'400.00','item_discount' =>'4.00','item_discount_type' =>'PERCENTAGE','is_addon' =>'0','status' =>'1','company_id' => $company],
['store_id' => $Ferns_and_Petals,'item_name' =>'Yellow Roses Bouquet & Black Forest Cake','item_description' =>'Yellow Roses Bouquet & Black Forest Cake' ,'picture' => url('/').'/images/order/items/yellow_roses_bouquet_&_black_forest_cake.png','store_category_id' =>'Flowers_N_Cakes','is_veg' =>'Pure Veg','item_price' =>'2000.00','item_discount' =>'2.00','item_discount_type' =>'PERCENTAGE','is_addon' =>'0','status' =>'1','company_id' => $company],
['store_id' => $Ferns_and_Petals,'item_name' =>'Red Roses & Pineapple Cake Combo','item_description' =>'Red Roses & Pineapple Cake Combo' ,'picture' => url('/').'/images/order/items/red_roses_&_pineapple_cake_combo.png','store_category_id' =>'Flowers_N_Cakes','is_veg' =>'Pure Veg','item_price' =>'1000.00','item_discount' =>'2.00','item_discount_type' =>'PERCENTAGE','is_addon' =>'0','status' =>'1','company_id' => $company],
['store_id' => $Bonchon_Chicken,'item_name' =>'French Fries Chicken','item_description' =>'Bonchon is a franchise specialized in Korean-style fried chicken with a variety of savory Asian fusion dishes and Korean specialties. Bonchon was born in Busan, South Korea and is raised in the heart of New York City' ,'picture' => url('/').'/images/order/items/french_fries_chicken.png','store_category_id' =>'Non_Veg','is_veg' =>'Non Veg','item_price' =>'100.00','item_discount' =>'0.00','item_discount_type' =>'PERCENTAGE','is_addon' =>'0','status' =>'1','company_id' => $company],
['store_id' => $Bonchon_Chicken,'item_name' =>'BonChon Chicken Bangkok','item_description' =>'BonChon Chicken is a global chain that spread through Korea and the USA before making its way back to Asia on the merits of its crispy, Korean-style fried chicken' ,'picture' => url('/').'/images/order/items/bonchon_chicken_bangkok.png','store_category_id' =>'Non_Veg','is_veg' =>'Non Veg','item_price' =>'250.00','item_discount' =>'0.00','item_discount_type' =>'PERCENTAGE','is_addon' =>'0','status' =>'1','company_id' => $company],
['store_id' => $Beer_Temple,'item_name' =>'Red Wine','item_description' =>'Summer is right around the corner! Looking for the best reds to take on your upcoming trips? These wines won\'t disappoint.' ,'picture' => url('/').'/images/order/items/red_wine.png','store_category_id' =>'Wine','is_veg' =>'Non Veg','item_price' =>'350.00','item_discount' =>'3.00','item_discount_type' =>'PERCENTAGE','is_addon' =>'0','status' =>'1','company_id' => $company],
['store_id' => $Beer_Temple,'item_name' =>'White Wine','item_description' =>'You donâ€™t have to spend a ton to impress your guests. We have plenty of highly rated white wines.' ,'picture' => url('/').'/images/order/items/white_wine.png','store_category_id' =>'Wine','is_veg' =>'Non Veg','item_price' =>'500.00','item_discount' =>'5.00','item_discount_type' =>'PERCENTAGE','is_addon' =>'0','status' =>'1','company_id' => $company],
['store_id' => $Beer_Temple,'item_name' =>'Tower Vodka','item_description' =>'This vodka proves that a top-shelf vodka doesn\'t always need a top-shelf price. Gluten-free, made from corn and distilled 6 times for a clean, crisp mouth feel with a silky smooth finish. Only 96 calories per serving! Double Gold -Seattle Spirits Comp; SF' ,'picture' => url('/').'/images/order/items/tower_vodka.png','store_category_id' =>'Vodka','is_veg' =>'Non Veg','item_price' =>'490.00','item_discount' =>'2.00','item_discount_type' =>'PERCENTAGE','is_addon' =>'0','status' =>'1','company_id' => $company],
['store_id' => $Beer_Temple,'item_name' =>'Tito\'s Handmade Vodka','item_description' =>'Designed to be savored by spirit connoisseurs. Micro-distilled in an old-fashioned pot still to provide more control over the distillation process and resulting in a spectacularly clean product. Only the heart of the run is taken, leaving behind residual' ,'picture' => url('/').'/images/order/items/tito\'s_handmade_vodka.png','store_category_id' =>'Vodka','is_veg' =>'Non Veg','item_price' =>'450.00','item_discount' =>'0.00','item_discount_type' =>'AMOUNT','is_addon' =>'0','status' =>'1','company_id' => $company],
['store_id' => $Beer_Temple,'item_name' =>'Tanqueray Gin','item_description' =>'Crafted using a time honored recipe of only the highest quality grains, the purest water, the most select juniper berries, finest botanicals, and a unique quadruple-distillation process.' ,'picture' => url('/').'/images/order/items/tanqueray_gin_.png','store_category_id' =>'Gin','is_veg' =>'Non Veg','item_price' =>'350.00','item_discount' =>'0.00','item_discount_type' =>'AMOUNT','is_addon' =>'0','status' =>'1','company_id' => $company],
['store_id' => $Beer_Temple,'item_name' =>'Hendricks Gin','item_description' =>'Made in small batches with a fully restored 19th-centrury Carter-Head Still, which "bathes" the ingredients in vapors instead of boiling, producing a smoother gin. A unique blend of botanicals, including Bulgarian Rose petal and cucumber. Kosher Certified' ,'picture' => url('/').'/images/order/items/hendricks_gin.png','store_category_id' =>'Gin','is_veg' =>'Non Veg','item_price' =>'590.00','item_discount' =>'0.00','item_discount_type' =>'AMOUNT','is_addon' =>'0','status' =>'1','company_id' => $company],
['store_id' => $Beer_Temple,'item_name' =>'Craft Beer','item_description' =>'Canned beers are lighter than bottles, unbreakable and keep summerâ€™s brightest sunshine from funk-i-fying the brew inside. Bring canned beers with you on all of your fun, summer adventures.' ,'picture' => url('/').'/images/order/items/craft_beer.png','store_category_id' =>'Beer','is_veg' =>'Non Veg','item_price' =>'290.00','item_discount' =>'0.00','item_discount_type' =>'PERCENTAGE','is_addon' =>'0','status' =>'1','company_id' => $company],
['store_id' => $Beer_Temple,'item_name' =>'Import Beer','item_description' =>'Designed to be savored by spirit connoisseurs. Micro-distilled in an old-fashioned pot still to provide more control over the distillation process and resulting in a spectacularly clean product. Only the heart of the run is taken, leaving behind residual' ,'picture' => url('/').'/images/order/items/import_beer.png','store_category_id' =>'Beer','is_veg' =>'Non Veg','item_price' =>'350.00','item_discount' =>'2.00','item_discount_type' =>'PERCENTAGE','is_addon' =>'0','status' =>'1','company_id' => $company],
['store_id' => $Go_Cheers,'item_name' =>'Import Beer','item_description' =>'Designed to be savored by spirit connoisseurs. Micro-distilled in an old-fashioned pot still to provide more control over the distillation process and resulting in a spectacularly clean product. Only the heart of the run is taken, leaving behind residual' ,'picture' => url('/').'/images/order/items/import_beer.png','store_category_id' =>'Beer','is_veg' =>'Non Veg','item_price' =>'400.00','item_discount' =>'0.00','item_discount_type' =>'PERCENTAGE','is_addon' =>'0','status' =>'1','company_id' => $company],    
['store_id' => $Go_Cheers,'item_name' =>'Craft Beer','item_description' =>'Canned beers are lighter than bottles, unbreakable and keep summerâ€™s brightest sunshine from funk-i-fying the brew inside. Bring canned beers with you on all of your fun, summer adventures.' ,'picture' => url('/').'/images/order/items/craft_beer.png','store_category_id' =>'Beer','is_veg' =>'Non Veg','item_price' =>'350.00','item_discount' =>'0.00','item_discount_type' =>'PERCENTAGE','is_addon' =>'0','status' =>'1','company_id' => $company],
['store_id' => $Go_Cheers,'item_name' =>'Jameson Irish Whiskey','item_description' =>'Wine Enthusiast -Ireland- A pot still whiskey blended of light and medium flavored whiskies that were triple distilled for exceptional smoothness. Matured in Bourbon and Sherry casks to produce a crisp, clean, mellow taste with sweet, spicy, vanilla tones' ,'picture' => url('/').'/images/order/items/jameson_irish_whiskey.png','store_category_id' =>'Whisky','is_veg' =>'Non Veg','item_price' =>'600.00','item_discount' =>'0.00','item_discount_type' =>'AMOUNT','is_addon' =>'0','status' =>'1','company_id' => $company],
['store_id' => $Go_Cheers,'item_name' =>'Jim Beam Bourbon Whiskey','item_description' =>'Kentucky- The world\'s number one bourbon. Jim Beam was founded in 1795 and has been operated by one family for seven generations. We\'ve always created bourbon our way, aging it twice as long as the law requires.' ,'picture' => url('/').'/images/order/items/jim_beam_bourbon_whiskey.png','store_category_id' =>'Whisky','is_veg' =>'Non Veg','item_price' =>'700.00','item_discount' =>'0.00','item_discount_type' =>'AMOUNT','is_addon' =>'0','status' =>'1','company_id' => $company],
['store_id' => $Marrybrown,'item_name' =>'Fresh Burger','item_description' =>'We know what a proper hamburger tastes like, and so should you. Try our famous Freshburger, and add something extra to your burger for a special layer of delicious!' ,'picture' => url('/').'/images/order/items/fresh_burger.png','store_category_id' =>'Veg','is_veg' =>'Pure Veg','item_price' =>'45.00','item_discount' =>'0.00','item_discount_type' =>'PERCENTAGE','is_addon' =>'0','status' =>'1','company_id' => $company],
['store_id' => $Go_Cheers,'item_name' =>'Famous Grouse','item_description' =>'Scotland- Fine malt whiskies are married with exceptional grain whiskies for an unusually long period in fully seasoned oak casks, thus creating a blend of the smoothest possible character.
' ,'picture' => url('/').'/images/order/items/famous_grouse.png','store_category_id' =>'Scotch','is_veg' =>'Non Veg','item_price' =>'500.00','item_discount' =>'0.00','item_discount_type' =>'AMOUNT','is_addon' =>'0','status' =>'1','company_id' => $company],
['store_id' => $Go_Cheers,'item_name' =>'Glenmorangie The Original','item_description' =>'Wine Enthusiast -Higlands, Scotland- "Delicate notes of candied apple, light toffee and pear drops...nuances of rose petals, carnations and lightly toasted malt. The palate entry is grainy and moderately sweet; at midpalate thereâ€™s a burst of red pepper' ,'picture' => url('/').'/images/order/items/glenmorangie_the_original.png','store_category_id' =>'Scotch','is_veg' =>'Non Veg','item_price' =>'450.00','item_discount' =>'0.00','item_discount_type' =>'AMOUNT','is_addon' =>'0','status' =>'1','company_id' => $company],
['store_id' => $Marrybrown,'item_name' =>'Fish & Chips','item_description' =>'2 pieces of 100% ocean fresh fish fillet, side with fries and mouth-watering dill pickle sauce and delicious vegetable salad.

' ,'picture' => url('/').'/images/order/items/fish_&_chips.png','store_category_id' =>'Non_Veg','is_veg' =>'Non Veg','item_price' =>'65.00','item_discount' =>'0.00','item_discount_type' =>'PERCENTAGE','is_addon' =>'0','status' =>'1','company_id' => $company],
['store_id' => $Drinkie,'item_name' =>'Rose Spirits','item_description' =>'USA- This premium Vodka has been distilled five times and infused with mango, passionfruit and blood orange liqueur, creating succulent flavor that will leave you satisfied. Enjoy in a cocktail or as a shot.' ,'picture' => url('/').'/images/order/items/rose_spirits.png','store_category_id' =>'Spirits','is_veg' =>'Non Veg','item_price' =>'380.00','item_discount' =>'2.00','item_discount_type' =>'AMOUNT','is_addon' =>'0','status' =>'1','company_id' => $company],
['store_id' => $Drinkie,'item_name' =>'Johnnie Walker Double Black','item_description' =>'"Kentucky straight bourbon whiskey finished in a port pipe. This is veteran master distiller Lincoln Henderson\'s newest creation, and it\'s a beauty. Richly textured, silky, and well-rounded, with ripe berried fruits, candied tangerine, light toffee, maple' ,'picture' => url('/').'/images/order/items/johnnie_walker_double_black.png','store_category_id' =>'Spirits','is_veg' =>'Non Veg','item_price' =>'480.00','item_discount' =>'4.00','item_discount_type' =>'AMOUNT','is_addon' =>'0','status' =>'1','company_id' => $company],
['store_id' => $Drinkie,'item_name' =>'Jim Beam Bourbon Whiskey','item_description' =>'Kentucky- The world\'s number one bourbon. Jim Beam was founded in 1795 and has been operated by one family for seven generations. We\'ve always created bourbon our way, aging it twice as long as the law requires.' ,'picture' => url('/').'/images/order/items/jim_beam_bourbon_whiskey.png','store_category_id' =>'Bourbon','is_veg' =>'Non Veg','item_price' =>'600.00','item_discount' =>'6.00','item_discount_type' =>'PERCENTAGE','is_addon' =>'0','status' =>'1','company_id' => $company],
['store_id' => $Drinkie,'item_name' =>'Woodford Reserve','item_description' =>'Kentucky- Spicy and forceful taking its flavor from the charred barrels that are used to age this bourbon. Charred oak, toffee, vanilla and pepper are the dominate flavors. A long lasting dry finish. Enjoy neat, with water, or with ice. Gold Medal - San F' ,'picture' => url('/').'/images/order/items/woodford_reserve.png','store_category_id' =>'Bourbon','is_veg' =>'Non Veg','item_price' =>'500.00','item_discount' =>'7.00','item_discount_type' =>'AMOUNT','is_addon' =>'0','status' =>'1','company_id' => $company],
['store_id' => $Liquor_Palace,'item_name' =>'Malibu Coconut Rum','item_description' =>'Barbados- Made in the spirit of traditional Caribbean flavored rums and filled with the fresh, natural taste of coconut, this smooth-drinking rum infuses any drink with a taste of the tropics. Perfect on its own or as a refreshing splash in any rum-based' ,'picture' => url('/').'/images/order/items/malibu_coconut_rum.png','store_category_id' =>'Rum','is_veg' =>'Non Veg','item_price' =>'450.00','item_discount' =>'0.00','item_discount_type' =>'PERCENTAGE','is_addon' =>'0','status' =>'1','company_id' => $company],
['store_id' => $Liquor_Palace,'item_name' =>'Sailor Jerry Spiced Rum','item_description' =>'US Virgin Islands- This 92 proof spiced rum is modeled after the rums that sailors used to create and is based on the recipe of Sailor Jerry Collins, a famous tattoo artist. Spiced with a hint of cherry and vanilla, it is very full-bodied but goes down sm' ,'picture' => url('/').'/images/order/items/sailor_jerry_spiced_rum.png','store_category_id' =>'Rum','is_veg' =>'Non Veg','item_price' =>'370.00','item_discount' =>'0.00','item_discount_type' =>'AMOUNT','is_addon' =>'0','status' =>'1','company_id' => $company],
['store_id' => $Marrybrown,'item_name' =>'Cheesy-O-Burger','item_description' =>'Juicy marinated whole chunk of boneless chicken thigh meat with a delicious slice of chicken patty topped with melted cheese, tasty Tower Burgerâ„¢ sauce, fresh hand cut iceberg lettuce and served on a warm toasted sesame seeded bun' ,'picture' => url('/').'/images/order/items/cheesy-o-burger.png','store_category_id' =>'Veg','is_veg' =>'Pure Veg','item_price' =>'100.00','item_discount' =>'0.00','item_discount_type' =>'PERCENTAGE','is_addon' =>'0','status' =>'1','company_id' => $company],
['store_id' => $Liquor_Palace,'item_name' =>'Bulleit Bourbon','item_description' =>'.Kentucky- Oaky, smoky, and spicy. The dry, clean flavor is mellow and spice with rye, not hot in the throat. This 90-proof Kentucky bourbon delivers a wonderfully complex taste with hints of vanilla and honey and a long smoky finish.
' ,'picture' => url('/').'/images/order/items/bulleit_bourbon_.png','store_category_id' =>'Bacardi_Limon','is_veg' =>'Non Veg','item_price' =>'600.00','item_discount' =>'0.00','item_discount_type' =>'AMOUNT','is_addon' =>'0','status' =>'1','company_id' => $company],
['store_id' => $Liquor_Palace,'item_name' =>'.Woodford Reserve','item_description' =>'Kentucky- Spicy and forceful taking its flavor from the charred barrels that are used to age this bourbon. Charred oak, toffee, vanilla and pepper are the dominate flavors. A long lasting dry finish. Enjoy neat, with water, or with ice. Gold Medal - San F' ,'picture' => url('/').'/images/order/items/.woodford_reserve.png','store_category_id' =>'Bacardi_Limon','is_veg' =>'Non Veg','item_price' =>'500.00','item_discount' =>'0.00','item_discount_type' =>'PERCENTAGE','is_addon' =>'0','status' =>'1','company_id' => $company],
['store_id' => $Marrybrown,'item_name' =>'Chick-A-Licious','item_description' =>'Hand-breaded 2 pieces of original recipe chicken, fresh cut coleslaw and fries. Complete with perfection black pepper sauce or mushroom sauce' ,'picture' => url('/').'/images/order/items/chick-a-licious.png','store_category_id' =>'Non_Veg','is_veg' =>'Non Veg','item_price' =>'100.00','item_discount' =>'0.00','item_discount_type' =>'PERCENTAGE','is_addon' =>'0','status' =>'1','company_id' => $company],
['store_id' => $Drankers_Park,'item_name' =>'Hennessy VS','item_description' =>'Cognac, France- A blend of over 40 eaux de vies from the four premier growing regions of Cognac. Beautiful golden color with a fruity sweetness and a hint of vanilla in the finish. A classic' ,'picture' => url('/').'/images/order/items/hennessy_vs.png','store_category_id' =>'Brandy','is_veg' =>'Non Veg','item_price' =>'400.00','item_discount' =>'0.00','item_discount_type' =>'AMOUNT','is_addon' =>'0','status' =>'1','company_id' => $company],
['store_id' => $Drankers_Park,'item_name' =>'.Hennessy VSOP','item_description' =>'Cognac, France- The world\'s first V.S.O.P Cognac Fine Champagne, Remy Martin V.S.O.P is a well-balanced and multi-layered cognac aged up to 14 years in French oak casks with vanilla, stone fruit and licorice notes.
' ,'picture' => url('/').'/images/order/items/.hennessy_vsop.png','store_category_id' =>'Brandy','is_veg' =>'Non Veg','item_price' =>'580.00','item_discount' =>'4.00','item_discount_type' =>'PERCENTAGE','is_addon' =>'0','status' =>'1','company_id' => $company],
['store_id' => $Drankers_Park,'item_name' =>'Clase Azul Reposado Tequila','item_description' =>'Mexico - Filtered before bottling so that the clean, clear taste of the 100% Agave tequila can be fully enjoyed by aficionados who crave the true original taste of premium agave.' ,'picture' => url('/').'/images/order/items/clase_azul_reposado_tequila.png','store_category_id' =>'Tequila','is_veg' =>'Non Veg','item_price' =>'500.00','item_discount' =>'0.00','item_discount_type' =>'AMOUNT','is_addon' =>'0','status' =>'1','company_id' => $company],
['store_id' => $Drankers_Park,'item_name' =>'Don Julio Blanco Tequila','item_description' =>'Mexico- Clean, clear and colorless. Holds aromas of agave, clean and fresh on the nose. The agave notes continue through the flavor, strong but not overpowering. Warm, smooth finish. Use in your favorite tequila cocktails.
' ,'picture' => url('/').'/images/order/items/don_julio_blanco_tequila.png','store_category_id' =>'Tequila','is_veg' =>'Non Veg','item_price' =>'650.00','item_discount' =>'2.00','item_discount_type' =>'AMOUNT','is_addon' =>'0','status' =>'1','company_id' => $company],
['store_id' => $Metisse_Restaurant,'item_name' =>'Panner Butter masala','item_description' =>'probably the most stereotypical of vegetarian foods. But there may be a reason for that. Tofu is pretty tasty, and it can be used in so many different ways. It\'s like a sponge, capable of soaking up a myriad of different flavors.' ,'picture' => url('/').'/images/order/items/panner_butter_masala.png','store_category_id' =>'Veg','is_veg' =>'Pure Veg','item_price' =>'75.00','item_discount' =>'0.00','item_discount_type' =>'PERCENTAGE','is_addon' =>'0','status' =>'1','company_id' => $company],
['store_id' => $Metisse_Restaurant,'item_name' =>'Pasta','item_description' =>'Pasta will never let you down when it comes to options: Stuffed shells, ravioli, stir-fry, and lo mein are just a few of our favorites. And, of course, the ultimate lazy vegetarian pasta' ,'picture' => url('/').'/images/order/items/pasta.png','store_category_id' =>'Veg','is_veg' =>'Pure Veg','item_price' =>'75.00','item_discount' =>'0.00','item_discount_type' =>'PERCENTAGE','is_addon' =>'0','status' =>'1','company_id' => $company],
['store_id' => $Cactus_Restaurant,'item_name' =>'Meals','item_description' =>'The famous chicken rice cooked in cloves garlic, crushed ginger and sesame oil. Comes with slices of boneless breast of chicken seasoned to perfection, freshly hand-cut acar, crispy papadam and topped with delicious MarrybrownÂ® chicken rice sauce. Comes' ,'picture' => url('/').'/images/order/items/meals.png','store_category_id' =>'Non_Veg','is_veg' =>'Non Veg','item_price' =>'150.00','item_discount' =>'0.00','item_discount_type' =>'PERCENTAGE','is_addon' =>'0','status' =>'1','company_id' => $company],
['store_id' => $Cactus_Restaurant,'item_name' =>'Bubur Ayam','item_description' =>'Test' ,'picture' => url('/').'/images/order/items/bubur_ayam.png','store_category_id' =>'Veg','is_veg' =>'Pure Veg','item_price' =>'100.00','item_discount' =>'0.00','item_discount_type' =>'PERCENTAGE','is_addon' =>'0','status' =>'1','company_id' => $company],
['store_id' => $Jevinik_Restaurant,'item_name' =>'White Coconut Rice','item_description' =>'Nigerian Coconut Rice with team White Coconut Rice always fighting with team Jollof Coconut Rice. You don\'t have to fight for these two meals because they are both delicious' ,'picture' => url('/').'/images/order/items/white_coconut_rice.png','store_category_id' =>'Non_Veg','is_veg' =>'Non Veg','item_price' =>'100.00','item_discount' =>'0.00','item_discount_type' =>'PERCENTAGE','is_addon' =>'0','status' =>'1','company_id' => $company],
['store_id' => $Fussion_Florist,'item_name' =>'Colorful Roses','item_description' =>'20 Roses Bunch of Mixed Colour' ,'picture' => url('/').'/images/order/items/colorful_roses.png','store_category_id' =>'Roses','is_veg' =>'Pure Veg','item_price' =>'50.00','item_discount' =>'0.00','item_discount_type' =>'PERCENTAGE','is_addon' =>'0','status' =>'1','company_id' => $company],
['store_id' => $Fussion_Florist,'item_name' =>'Red Rose Bunch','item_description' =>'Beautiful Bunch of 12 Red Roses to please any one.' ,'picture' => url('/').'/images/order/items/red_rose_bunch.png','store_category_id' =>'Roses','is_veg' =>'Pure Veg','item_price' =>'60.00','item_discount' =>'0.00','item_discount_type' =>'PERCENTAGE','is_addon' =>'0','status' =>'1','company_id' => $company],
['store_id' => $Fussion_Florist,'item_name' =>'Orange Carnation','item_description' =>'12 Stalks Orange Carnation' ,'picture' => url('/').'/images/order/items/orange_carnation.png','store_category_id' =>'Carnations','is_veg' =>'Pure Veg','item_price' =>'100.00','item_discount' =>'0.00','item_discount_type' =>'PERCENTAGE','is_addon' =>'0','status' =>'1','company_id' => $company],
['store_id' => $Fussion_Florist,'item_name' =>'Red Carnation','item_description' =>'12 Red Carnation Bunch' ,'picture' => url('/').'/images/order/items/red_carnation.png','store_category_id' =>'Carnations','is_veg' =>'Non Veg','item_price' =>'120.00','item_discount' =>'0.00','item_discount_type' =>'PERCENTAGE','is_addon' =>'0','status' =>'1','company_id' => $company],
['store_id' => $Just_FlowerZ,'item_name' =>'25 Red Gerbera','item_description' =>'5 Red Gerberas Bunch' ,'picture' => url('/').'/images/order/items/25_red_gerbera.png','store_category_id' =>'Gerberas','is_veg' =>'Pure Veg','item_price' =>'100.00','item_discount' =>'2.00','item_discount_type' =>'PERCENTAGE','is_addon' =>'0','status' =>'1','company_id' => $company],
['store_id' => $Just_FlowerZ,'item_name' =>'Bright Gerberas','item_description' =>'Basket of 15 Yellow fresh gerberas' ,'picture' => url('/').'/images/order/items/bright_gerberas.png','store_category_id' =>'Gerberas','is_veg' =>'Pure Veg','item_price' =>'120.00','item_discount' =>'2.00','item_discount_type' =>'AMOUNT','is_addon' =>'0','status' =>'1','company_id' => $company],
['store_id' => $Just_FlowerZ,'item_name' =>'Mix Flower Bunch','item_description' =>'Bunch of 12 Carnations and 7 Roses' ,'picture' => url('/').'/images/order/items/mix_flower_bunch.png','store_category_id' =>'Mix_Flowers','is_veg' =>'Pure Veg','item_price' =>'240.00','item_discount' =>'4.00','item_discount_type' =>'PERCENTAGE','is_addon' =>'0','status' =>'1','company_id' => $company],
['store_id' => $Just_FlowerZ,'item_name' =>'Tall Exotic Arrangement','item_description' =>'3-4 feet tall exotic arrangement of 10 blue orchids, 24 white carnations and 50 roses.
Send this stunning and gorgeous arrangement to cherish the special moments of special day in your loved one\'s life' ,'picture' => url('/').'/images/order/items/tall_exotic_arrangement.png','store_category_id' =>'Mix_Flowers','is_veg' =>'Pure Veg','item_price' =>'150.00','item_discount' =>'6.00','item_discount_type' =>'PERCENTAGE','is_addon' =>'0','status' =>'1','company_id' => $company],
['store_id' => $Royal_Blooms,'item_name' =>'Pink Flowers','item_description' =>'Elegance n love' ,'picture' => url('/').'/images/order/items/pink_flowers_.png','store_category_id' =>'Flowers_By_Colors','is_veg' =>'Pure Veg','item_price' =>'150.00','item_discount' =>'6.00','item_discount_type' =>'PERCENTAGE','is_addon' =>'0','status' =>'1','company_id' => $company],
['store_id' => $Royal_Blooms,'item_name' =>'Purple Flowers','item_description' =>'Colorful Fifteen Orchids Arrangement' ,'picture' => url('/').'/images/order/items/purple_flowers.png','store_category_id' =>'Flowers_By_Colors','is_veg' =>'Pure Veg','item_price' =>'190.00','item_discount' =>'4.00','item_discount_type' =>'AMOUNT','is_addon' =>'0','status' =>'1','company_id' => $company],
['store_id' => $Royal_Blooms,'item_name' =>'Flowers and fruits','item_description' =>'Flowers Arrangment with Fruits' ,'picture' => url('/').'/images/order/items/flowers_and_fruits.png','store_category_id' =>'Flowers_By_Combo','is_veg' =>'Pure Veg','item_price' =>'200.00','item_discount' =>'0.00','item_discount_type' =>'PERCENTAGE','is_addon' =>'0','status' =>'1','company_id' => $company],
['store_id' => $Royal_Blooms,'item_name' =>' Flowers and teddy','item_description' =>'Teddy on Top' ,'picture' => url('/').'/images/order/items/_flowers_and_teddy.png','store_category_id' =>'Flowers_By_Combo','is_veg' =>'Pure Veg','item_price' =>'300.00','item_discount' =>'0.00','item_discount_type' =>'PERCENTAGE','is_addon' =>'0','status' =>'1','company_id' => $company],
['store_id' => $Flora,'item_name' =>'Heart shaped','item_description' =>'Heart Shaped Arrangement of 30 Red Roses.' ,'picture' => url('/').'/images/order/items/heart_shaped.png','store_category_id' =>'Flowers_By_Design','is_veg' =>'Pure Veg','item_price' =>'400.00','item_discount' =>'0.00','item_discount_type' =>'PERCENTAGE','is_addon' =>'0','status' =>'1','company_id' => $company],
['store_id' => $Flora,'item_name' =>'Basket Arrangements','item_description' =>'Basket of beauty' ,'picture' => url('/').'/images/order/items/basket_arrangements_.png','store_category_id' =>'Flowers_By_Design','is_veg' =>'Pure Veg','item_price' =>'450.00','item_discount' =>'0.00','item_discount_type' =>'AMOUNT','is_addon' =>'0','status' =>'1','company_id' => $company],
['store_id' => $Flora,'item_name' =>'Under 499','item_description' =>'Freshness Personified' ,'picture' => url('/').'/images/order/items/under_499.png','store_category_id' =>'Flowers_By_Price','is_veg' =>'Pure Veg','item_price' =>'499.00','item_discount' =>'15.00','item_discount_type' =>'AMOUNT','is_addon' =>'0','status' =>'1','company_id' => $company],
['store_id' => $Flora,'item_name' =>'500-999','item_description' =>'Orchids fascination' ,'picture' => url('/').'/images/order/items/500-999.png','store_category_id' =>'Flowers_By_Price','is_veg' =>'Non Veg','item_price' =>'1000.00','item_discount' =>'10.00','item_discount_type' =>'AMOUNT','is_addon' =>'0','status' =>'1','company_id' => $company],
['store_id' => $MooMix,'item_name' =>'Noble Orchids','item_description' =>'6 Blue Orchids wrapped in Cellophane Paper' ,'picture' => url('/').'/images/order/items/noble_orchids.png','store_category_id' =>'Orchids_','is_veg' =>'Pure Veg','item_price' =>'120.00','item_discount' =>'2.00','item_discount_type' =>'AMOUNT','is_addon' =>'0','status' =>'1','company_id' => $company],
['store_id' => $MooMix,'item_name' =>'Winter Orchids','item_description' =>'10 White Orchids in special paper' ,'picture' => url('/').'/images/order/items/winter_orchids.png','store_category_id' =>'Orchids_','is_veg' =>'Pure Veg','item_price' =>'140.00','item_discount' =>'2.00','item_discount_type' =>'AMOUNT','is_addon' =>'0','status' =>'1','company_id' => $company],
['store_id' => $MooMix,'item_name' =>'Stunning hot lilies','item_description' =>'4 Asiatic Pink Lilies and 12 Red Roses' ,'picture' => url('/').'/images/order/items/stunning_hot_lilies.png','store_category_id' =>'Lilies','is_veg' =>'Pure Veg','item_price' =>'150.00','item_discount' =>'4.00','item_discount_type' =>'AMOUNT','is_addon' =>'0','status' =>'1','company_id' => $company],
['store_id' => $MooMix,'item_name' =>'Blush Pink Lilies','item_description' =>'10 Pink Asiatic Lilies' ,'picture' => url('/').'/images/order/items/blush_pink_lilies.png','store_category_id' =>'Lilies','is_veg' =>'Pure Veg','item_price' =>'160.00','item_discount' =>'4.00','item_discount_type' =>'AMOUNT','is_addon' =>'0','status' =>'1','company_id' => $company],
['store_id' => $Walmart,'item_name' =>'Hard soda','item_description' =>'Hard soda, also referred to as flavored beer, is a type of alcoholic beverage and craft beer that is manufactured in the style of a soft drink' ,'picture' => url('/').'/images/order/items/hard_soda.png','store_category_id' =>'Beverages','is_veg' =>'Pure Veg','item_price' =>'30.00','item_discount' =>'4.00','item_discount_type' =>'PERCENTAGE','is_addon' =>'0','status' =>'1','company_id' => $company],
['store_id' => $Walmart,'item_name' =>'Popcorn','item_description' =>'Popcorn is a variety of corn kernel, which expands and puffs up when heated. A popcorn kernel\'s strong hull contains the seed\'s hard, starchy endosperm with 14â€“20% moisture, which turns to steam as the kernel is heated' ,'picture' => url('/').'/images/order/items/popcorn.png','store_category_id' =>'Beverages','is_veg' =>'Pure Veg','item_price' =>'60.00','item_discount' =>'0.00','item_discount_type' =>'PERCENTAGE','is_addon' =>'0','status' =>'1','company_id' => $company],
['store_id' => $Walmart,'item_name' =>'Snacky Nuts','item_description' =>'A nut is a fruit composed of an inedible hard shell and a seed, which is generally edible. In general usage, a wide variety of dried seeds are called nuts, but in a botanical context "nut" implies that the shell does not open to release the seed' ,'picture' => url('/').'/images/order/items/snacky_nuts.png','store_category_id' =>'Beverages','is_veg' =>'Pure Veg','item_price' =>'38.00','item_discount' =>'0.00','item_discount_type' =>'PERCENTAGE','is_addon' =>'0','status' =>'1','company_id' => $company],
['store_id' => $Walmart,'item_name' =>'Bread','item_description' =>'Thereâ€™s nothing like taking a loaf of fresh yeast bread out of the oven. Just the enticing scent alone makes one of the worldâ€™s most celebrated foods worth baking! From a handful of ingredientsâ€”at its most basic flour, yeast, water, and saltâ€”to th' ,'picture' => url('/').'/images/order/items/bread__.png','store_category_id' =>'Bread/Bakery','is_veg' =>'Pure Veg','item_price' =>'20.00','item_discount' =>'0.00','item_discount_type' =>'PERCENTAGE','is_addon' =>'0','status' =>'1','company_id' => $company],
['store_id' => $Walmart,'item_name' =>'Cooking Oils','item_description' =>'.Cooking oil is plant, animal, or synthetic fat used in frying, baking, and other types of cooking. It is also used in food preparation and flavouring not involving heat, such as salad dressings and bread dips, and in this sense might be more accurately t' ,'picture' => url('/').'/images/order/items/cooking_oils.png','store_category_id' =>'Staples','is_veg' =>'Pure Veg','item_price' =>'180.00','item_discount' =>'0.00','item_discount_type' =>'PERCENTAGE','is_addon' =>'0','status' =>'1','company_id' => $company],
['store_id' => $Walmart,'item_name' =>'Cakes','item_description' =>'Layer cakes, cupcakes, snack cakes, roulades, and even cheesecakesâ€”the cake category is vast. Most cakes are often classified into two categories: whether they contain fat, such as butter or oil (shortened cakes) or whether they contain little or no fat' ,'picture' => url('/').'/images/order/items/cakes__.png','store_category_id' =>'Bread/Bakery','is_veg' =>'Pure Veg','item_price' =>'86.00','item_discount' =>'0.00','item_discount_type' =>'PERCENTAGE','is_addon' =>'0','status' =>'1','company_id' => $company],
['store_id' => $Walmart,'item_name' =>'Custard','item_description' =>'Custards are thick, rich, creamy desserts typically made from eggs and milk or cream. They can be sweet or savory and flavored loads of different ways. Made on the stovetop or baked, they range from cheesecake and flan to ice cream, pastry cream, and even' ,'picture' => url('/').'/images/order/items/custard.png','store_category_id' =>'Bread/Bakery','is_veg' =>'Pure Veg','item_price' =>'20.00','item_discount' =>'0.00','item_discount_type' =>'PERCENTAGE','is_addon' =>'0','status' =>'1','company_id' => $company],
['store_id' => $Walmart,'item_name' =>'Ghee ','item_description' =>'Ghee, is a class of clarified butter that originated in ancient India. It is commonly used in Middle Eastern cuisine, cuisine of the Indian subcontinent, Southeast Asian cuisine, traditional medicine, and religious rituals' ,'picture' => url('/').'/images/order/items/ghee___.png','store_category_id' =>'Staples','is_veg' =>'Pure Veg','item_price' =>'45.00','item_discount' =>'0.00','item_discount_type' =>'PERCENTAGE','is_addon' =>'0','status' =>'1','company_id' => $company],
['store_id' => $Walmart,'item_name' =>'Wheat','item_description' =>'Wheat is a grass widely cultivated for its seed, a cereal grain which is a worldwide staple food. The many species of wheat together make up the genus Triticum; the most widely grown is common wheat' ,'picture' => url('/').'/images/order/items/wheat.png','store_category_id' =>'Staples','is_veg' =>'Pure Veg','item_price' =>'50.00','item_discount' =>'0.00','item_discount_type' =>'PERCENTAGE','is_addon' =>'0','status' =>'1','company_id' => $company],
['store_id' => $Whole_Foods,'item_name' =>'Milk','item_description' =>'Milk is a nutrient-rich, white liquid food produced by the mammary glands of mammals. It is the primary source of nutrition for infant mammals before they are able to digest other types of food  ' ,'picture' => url('/').'/images/order/items/milk__.png','store_category_id' =>'Dairy','is_veg' =>'Pure Veg','item_price' =>'10.00','item_discount' =>'0.00','item_discount_type' =>'PERCENTAGE','is_addon' =>'0','status' =>'1','company_id' => $company],
['store_id' => $Whole_Foods,'item_name' =>'Cheese','item_description' =>'Cheese is a dairy product derived from milk that is produced in a wide range of flavors, textures, and forms by coagulation of the milk protein casein. It comprises proteins and fat from milk, usually the milk of cows, buffalo, goats, or sheep' ,'picture' => url('/').'/images/order/items/cheese__.png','store_category_id' =>'Dairy','is_veg' =>'Pure Veg','item_price' =>'30.00','item_discount' =>'0.00','item_discount_type' =>'PERCENTAGE','is_addon' =>'0','status' =>'1','company_id' => $company],
['store_id' => $Whole_Foods,'item_name' =>'Soya Milk','item_description' =>'Soy milk or soymilk is a plant-based drink produced by soaking and grinding soybeans, boiling the mixture, and filtering out remaining particulates. It is a stable emulsion of oil, water, and protein. Its original form is a natural by-product' ,'picture' => url('/').'/images/order/items/soya_milk.png','store_category_id' =>'Dairy','is_veg' =>'Pure Veg','item_price' =>'40.00','item_discount' =>'0.00','item_discount_type' =>'PERCENTAGE','is_addon' =>'0','status' =>'1','company_id' => $company],
['store_id' => $Whole_Foods,'item_name' =>'Cocoa Powder','item_description' =>'Trader Joeâ€™s sells unsweetened cocoa powder that is delicious in my recipe for Tâ€™s Dreamy Chocolate Sauce for our Dessert Nachos for Breakfast! YUM!!! I also buy raw cacao powder.' ,'picture' => url('/').'/images/order/items/cocoa_powder_.png','store_category_id' =>'Dry/Baking_Goods','is_veg' =>'Pure Veg','item_price' =>'40.00','item_discount' =>'0.00','item_discount_type' =>'PERCENTAGE','is_addon' =>'0','status' =>'1','company_id' => $company],
['store_id' => $Whole_Foods,'item_name' =>'Chocolate Chips','item_description' =>'prefer to use cacao nibs (and cacao/cocoa powder) whenever possible. My husband and kids really like chocolate chips. Look at the ingredient label to make sure that they do not contain any dairy' ,'picture' => url('/').'/images/order/items/chocolate_chips.png','store_category_id' =>'Dry/Baking_Goods','is_veg' =>'Pure Veg','item_price' =>'40.00','item_discount' =>'0.00','item_discount_type' =>'PERCENTAGE','is_addon' =>'0','status' =>'1','company_id' => $company],
['store_id' => $ShopRite,'item_name' =>'Chocolates','item_description' =>'Chocolate is a usually sweet, brown food preparation of roasted and ground cacao seeds that is made in the form of a liquid, paste, or in a block, or used as a flavoring ingredient in other foods ' ,'picture' => url('/').'/images/order/items/chocolates__.png','store_category_id' =>'Chocolates_&_Sweets','is_veg' =>'Pure Veg','item_price' =>'45.00','item_discount' =>'0.00','item_discount_type' =>'PERCENTAGE','is_addon' =>'0','status' =>'1','company_id' => $company],
['store_id' => $ShopRite,'item_name' =>'Gums','item_description' =>'The purpose of GEMS/Food is to compile data on food contamination and human exposure from different countries for global synthesis, evaluation and presentation.' ,'picture' => url('/').'/images/order/items/gums.png','store_category_id' =>'Chocolates_&_Sweets','is_veg' =>'Pure Veg','item_price' =>'5.00','item_discount' =>'0.00','item_discount_type' =>'PERCENTAGE','is_addon' =>'0','status' =>'1','company_id' => $company],
['store_id' => $ShopRite,'item_name' =>'Mouth Freshner','item_description' =>'Spraymintt is a one second mouth freshener that makes you kiss ready in just one second. With its natural formulation and no side effects it is the best solution for instant mouth freshener' ,'picture' => url('/').'/images/order/items/mouth_freshner.png','store_category_id' =>'Chocolates_&_Sweets','is_veg' =>'Pure Veg','item_price' =>'35.00','item_discount' =>'0.00','item_discount_type' =>'PERCENTAGE','is_addon' =>'0','status' =>'1','company_id' => $company],
['store_id' => $ShopRite,'item_name' =>'Friut Drinks','item_description' =>'.Juice is a drink made from the extraction or pressing of the natural liquid contained in fruit and vegetables. It can also refer to liquids that are flavored with concentrate or other biological food sources, such as meat or seafood, such as clam juice' ,'picture' => url('/').'/images/order/items/friut_drinks.png','store_category_id' =>'Soft_Drinks','is_veg' =>'Pure Veg','item_price' =>'35.00','item_discount' =>'0.00','item_discount_type' =>'PERCENTAGE','is_addon' =>'0','status' =>'1','company_id' => $company],
['store_id' => $ShopRite,'item_name' =>'Energy Drink','item_description' =>'An energy drink is a type of drink containing sugar and stimulant compounds, usually caffeine, which is marketed as providing mental and physical stimulation. They may or may not be carbonated and may also contain other sweeteners, herbal extracts, taurin' ,'picture' => url('/').'/images/order/items/energy_drink.png','store_category_id' =>'Soft_Drinks','is_veg' =>'Pure Veg','item_price' =>'50.00','item_discount' =>'0.00','item_discount_type' =>'PERCENTAGE','is_addon' =>'0','status' =>'1','company_id' => $company],
['store_id' => $ShopRite,'item_name' =>'Noodles','item_description' =>'Noodles are unleavened dough which is stretched, extruded, or rolled flat and cut into one of a variety of shapes which usually include long, thin strips, or waves, helices, tubes, strings, or shells, or folded over, or cut into other shapes     ' ,'picture' => url('/').'/images/order/items/noodles.png','store_category_id' =>'Packaged_food','is_veg' =>'Pure Veg','item_price' =>'50.00','item_discount' =>'0.00','item_discount_type' =>'PERCENTAGE','is_addon' =>'0','status' =>'1','company_id' => $company],
['store_id' => $ShopRite,'item_name' =>'Pasta','item_description' =>'Pasta is type of noodle typically made from an unleavened dough of durum wheat flour mixed with water or eggs, and formed into sheets or various shapes, then cooked by boiling or baking' ,'picture' => url('/').'/images/order/items/pasta.png','store_category_id' =>'Packaged_food','is_veg' =>'Pure Veg','item_price' =>'75.00','item_discount' =>'0.00','item_discount_type' =>'PERCENTAGE','is_addon' =>'0','status' =>'1','company_id' => $company],
['store_id' => $Marketside,'item_name' =>'Toor dal','item_description' =>'perennial legume from the family Fabaceae. Since its domestication in the Indian subcontinent at least 3,500 years ago, its seeds have become a common food in Asia, Africa, and Latin America' ,'picture' => url('/').'/images/order/items/toor_dal.png','store_category_id' =>'Dals_and_Pulses','is_veg' =>'Pure Veg','item_price' =>'45.00','item_discount' =>'0.00','item_discount_type' =>'PERCENTAGE','is_addon' =>'0','status' =>'1','company_id' => $company],
['store_id' => $Marketside,'item_name' =>'Urad dal','item_description' =>'Vigna mungo, black gram, urad bean, urid bean, minapa pappu, mungo bean or black matpe bean is a bean grown in the Indian subcontinent. Like its relative, the mung bean, it has been reclassified from the Phaseolus to the Vigna genus' ,'picture' => url('/').'/images/order/items/urad_dal_.png','store_category_id' =>'Dals_and_Pulses','is_veg' =>'Pure Veg','item_price' =>'45.00','item_discount' =>'0.00','item_discount_type' =>'PERCENTAGE','is_addon' =>'0','status' =>'1','company_id' => $company],
['store_id' => $Marketside,'item_name' =>'Moong Dall','item_description' =>'The mung bean, alternatively known as the green gram, maash, or moong , is a plant species in the legume family. The mung bean is mainly cultivated in East Asia, Southeast Asia and Indian subcontinent' ,'picture' => url('/').'/images/order/items/moong_dall.png','store_category_id' =>'Dals_and_Pulses','is_veg' =>'Pure Veg','item_price' =>'65.00','item_discount' =>'0.00','item_discount_type' =>'PERCENTAGE','is_addon' =>'0','status' =>'1','company_id' => $company],
['store_id' => $Marketside,'item_name' =>'Pickles','item_description' =>'A pickled cucumber is a cucumber that has been pickled in a brine, vinegar, or other solution and left to ferment for a period of time, by either immersing the cucumbers in an acidic solution or through souring by lacto-fermentation.' ,'picture' => url('/').'/images/order/items/pickles__.png','store_category_id' =>'Pickles_&_Chutney','is_veg' =>'Pure Veg','item_price' =>'55.00','item_discount' =>'0.00','item_discount_type' =>'PERCENTAGE','is_addon' =>'0','status' =>'1','company_id' => $company],
['store_id' => $Marketside,'item_name' =>'Chutney','item_description' =>'Chutney is a sauce or a dry base for a sauce, originating from the Indian subcontinent, used with the cuisines of the Indian subcontinent, that can include such forms as a spicy coconut dip, a tomato relish, a ground peanut garnish or a dahi, cucumber, an' ,'picture' => url('/').'/images/order/items/chutney.png','store_category_id' =>'Pickles_&_Chutney','is_veg' =>'Pure Veg','item_price' =>'35.00','item_discount' =>'0.00','item_discount_type' =>'PERCENTAGE','is_addon' =>'0','status' =>'1','company_id' => $company],
['store_id' => $Marketside,'item_name' =>'Ketchups ','item_description' =>'Ketchup is a sauce used as a condiment. Originally, recipes used egg whites, mushrooms, oysters, mussels, or walnuts, among other ingredients, but now the unmodified term usually refers to tomato ketchup' ,'picture' => url('/').'/images/order/items/ketchups___.png','store_category_id' =>'Ketchups_&_Spreads','is_veg' =>'Pure Veg','item_price' =>'60.00','item_discount' =>'0.00','item_discount_type' =>'PERCENTAGE','is_addon' =>'0','status' =>'1','company_id' => $company],
['store_id' => $Marketside,'item_name' =>'Dip Spreads','item_description' =>'.A spread is a food that is spread, generally with a knife, onto foods such as bread and crackers. Spreads are added to food to enhance the flavor or texture of the food, which may be considered bland without it. Butter and soft cheeses are typical spread' ,'picture' => url('/').'/images/order/items/dip_spreads.png','store_category_id' =>'Ketchups_&_Spreads','is_veg' =>'Pure Veg','item_price' =>'35.00','item_discount' =>'0.00','item_discount_type' =>'PERCENTAGE','is_addon' =>'0','status' =>'1','company_id' => $company],
['store_id' => $Southeastern_Grocers,'item_name' =>'Powdered Spices','item_description' =>'Spices are used in different forms: whole, chopped, ground, roasted, sautÃ©ed, fried, and as topping. They blend food to extract the nutrients and bind them in a palatable form. Some spices are added at the end as a flavouring and are typically heated in' ,'picture' => url('/').'/images/order/items/powdered_spices.png','store_category_id' =>'Masalas_&_Spices','is_veg' =>'Pure Veg','item_price' =>'30.00','item_discount' =>'0.00','item_discount_type' =>'PERCENTAGE','is_addon' =>'0','status' =>'1','company_id' => $company],
['store_id' => $Southeastern_Grocers,'item_name' =>'Whole Spices','item_description' =>'Fenugreek is used to add flavor to meat dishes. It is also considered as an aphrodisiac. Garam Masala â€“ meaning â€œhot spicesâ€ - is a mixture of ground spices (recipes vary) (cloves, cardamom, cumin, peppercorns and cinnamon, bay leaves). It is far be' ,'picture' => url('/').'/images/order/items/whole_spices.png','store_category_id' =>'Masalas_&_Spices','is_veg' =>'Pure Veg','item_price' =>'30.00','item_discount' =>'0.00','item_discount_type' =>'PERCENTAGE','is_addon' =>'0','status' =>'1','company_id' => $company],
['store_id' => $Southeastern_Grocers,'item_name' =>'Cooking Paste','item_description' =>'A food paste is a semi-liquid colloidal suspension, emulsion, or aggregation used in food preparation or eaten directly as a spread. Pastes are often highly spicy or aromatic, are often prepared well in advance of actual usage, and are often made into a p' ,'picture' => url('/').'/images/order/items/cooking_paste.png','store_category_id' =>'Masalas_&_Spices','is_veg' =>'Pure Veg','item_price' =>'50.00','item_discount' =>'0.00','item_discount_type' =>'PERCENTAGE','is_addon' =>'0','status' =>'1','company_id' => $company],
['store_id' => $Southeastern_Grocers,'item_name' =>'Cashew Nuts','item_description' =>'The cashew tree is a tropical evergreen tree that produces the cashew seed and the cashew apple. It can grow as high as 14 m,  growing up to 6 m, has proved more profitable, with earlier maturity and higher yields' ,'picture' => url('/').'/images/order/items/cashew_nuts.png','store_category_id' =>'Dry_Fruits,_Nuts_&_Seeds','is_veg' =>'Pure Veg','item_price' =>'50.00','item_discount' =>'0.00','item_discount_type' =>'PERCENTAGE','is_addon' =>'0','status' =>'1','company_id' => $company],
['store_id' => $Southeastern_Grocers,'item_name' =>'Edible Seeds','item_description' =>'Edible seeds are angiosperms, but a few are gymnosperms. The most important global seed food source, by weight, is cereals, followed by legumes, and nuts.' ,'picture' => url('/').'/images/order/items/edible_seeds.png','store_category_id' =>'Dry_Fruits,_Nuts_&_Seeds','is_veg' =>'Pure Veg','item_price' =>'30.00','item_discount' =>'0.00','item_discount_type' =>'PERCENTAGE','is_addon' =>'0','status' =>'1','company_id' => $company],
['store_id' => $Southeastern_Grocers,'item_name' =>'Dried Fruits','item_description' =>'Dried fruit is fruit from which the majority of the original water content has been removed either naturally, through sun drying, or through the use of specialized dryers or dehydrators' ,'picture' => url('/').'/images/order/items/dried_fruits.png','store_category_id' =>'Dry_Fruits,_Nuts_&_Seeds','is_veg' =>'Pure Veg','item_price' =>'40.00','item_discount' =>'0.00','item_discount_type' =>'PERCENTAGE','is_addon' =>'0','status' =>'1','company_id' => $company],
['store_id' => $Southeastern_Grocers,'item_name' =>'Health Powder Mix','item_description' =>'Multigrain Health Drink. This is the ultimate health drink powder for kids, with ingredients like millet, horse gram, sago, almonds, pistachios, cashew nuts and many others.' ,'picture' => url('/').'/images/order/items/health_powder_mix.png','store_category_id' =>'Health_Drink_Mix','is_veg' =>'Pure Veg','item_price' =>'50.00','item_discount' =>'0.00','item_discount_type' =>'PERCENTAGE','is_addon' =>'0','status' =>'1','company_id' => $company],
        ]);
        
        Schema::connection('order')->enableForeignKeyConstraints();
    }
}